"""The equation library: sections, LaTeX, plain-English notes and implementing functions."""

SECTIONS = [
    ("returns", "I. Returns, probability, and statistics"),
    ("regression", "II. Regression and econometrics"),
    ("timeseries", "III. Time-series models"),
    ("volatility", "IV. Volatility models"),
    ("stochastic", "V. Stochastic processes"),
    ("ml", "VI. Machine learning"),
    ("nn", "VII. Neural networks / deep learning"),
    ("portfolio", "VIII. Portfolio theory, risk, and asset pricing"),
    ("fixed_income", "IX. Fixed income"),
    ("forwards", "X. Forwards and futures"),
    ("options", "XI. Options"),
    ("swaps", "XII. Swaps and total return swaps"),
    ("credit", "XIII. Credit and CDS"),
]

_P = "finsim.quant."

# (id, section, name, latex, note, fn, metric)
_ROWS = [
    # ------------------------------------------------------------------ I
    ("1", "returns", "Simple return", r"R_t = \frac{P_t - P_{t-1} + D_t}{P_{t-1}}",
     "The percentage gain or loss over one period, including any dividend paid.",
     "stats.simple_return", "ret_1d"),
    ("2", "returns", "Log return", r"r_t = \ln\left(\frac{P_t}{P_{t-1}}\right)",
     "A continuously compounded return that adds up neatly across periods.",
     "stats.log_return", "log_ret_1d"),
    ("3", "returns", "Cumulative simple return", r"R_{0,T} = \prod_{t=1}^{T}(1 + R_t) - 1",
     "The total growth of an investment over several periods with compounding.",
     "stats.cumulative_return", "ret_1m"),
    ("4", "returns", "Cumulative log return", r"r_{0,T} = \sum_{t=1}^{T} r_t",
     "Total log growth over a horizon, found by simply summing daily log returns.",
     "stats.cumulative_log_return", "cum_log_1y"),
    ("5", "returns", "Annualized return", r"R_{ann} = \left[\prod_{t=1}^{n}(1 + R_t)\right]^{A/n} - 1",
     "Converts growth over any horizon into a per-year rate so assets can be compared.",
     "stats.annualized_return", "ann_return"),
    ("6", "returns", "Arithmetic mean", r"\bar{x} = \frac{1}{N}\sum_{i=1}^{N} x_i",
     "The average period return; the best single-period expected-return estimate.",
     "stats.mean", "mean_ret"),
    ("7", "returns", "Geometric mean return", r"R_g = \left[\prod_{t=1}^{n}(1 + R_t)\right]^{1/n} - 1",
     "The compound average return actually earned per period, always at or below the arithmetic mean.",
     "stats.geometric_mean_return", "geo_mean"),
    ("8", "returns", "Sample variance", r"s^2 = \frac{1}{N-1}\sum_{i=1}^{N}(x_i - \bar{x})^2",
     "Measures how widely returns scatter around their average.",
     "stats.variance", "vol_ann"),
    ("9", "returns", "Standard deviation", r"s = \sqrt{s^2}",
     "Volatility in the same units as returns; the standard measure of total risk.",
     "stats.stdev", "vol_ann"),
    ("10", "returns", "Covariance", r"\operatorname{Cov}(X,Y) = \frac{1}{N-1}\sum_{i=1}^{N}(x_i - \bar{x})(y_i - \bar{y})",
     "Shows whether two assets tend to move together, the building block of diversification.",
     "stats.covariance", "corr_mkt"),
    ("11", "returns", "Correlation", r"\rho_{XY} = \frac{\operatorname{Cov}(X,Y)}{\sigma_X \sigma_Y}",
     "Co-movement scaled to between -1 and 1; low correlation means better diversification.",
     "stats.correlation", "corr_mkt"),
    ("12", "returns", "Z-score", r"z = \frac{x - \mu}{\sigma}",
     "How many standard deviations a value sits from its average, flagging stretched prices.",
     "stats.zscore", "zscore_50"),
    ("13", "returns", "Expected value", r"E[X] = \sum_i p_i x_i \quad\text{or}\quad E[X] = \int x f(x)\,dx",
     "The probability-weighted average outcome of a bet or scenario set.",
     "stats.expected_value", None),
    ("14", "returns", "Conditional expectation", r"E[X \mid Y = y] = \sum_x x\, P(X = x \mid Y = y)",
     "The average outcome given some information, such as returns in a given market regime.",
     "stats.conditional_expectation", None),
    ("15", "returns", "Bayes' theorem", r"P(A \mid B) = \frac{P(B \mid A)\,P(A)}{P(B)}",
     "Updates a belief when new evidence arrives, such as revising a default view after news.",
     "stats.bayes", None),
    ("16", "returns", "Skewness", r"\text{Skew} = \frac{\frac{1}{N}\sum (x_i - \bar{x})^3}{\left[\frac{1}{N}\sum (x_i - \bar{x})^2\right]^{3/2}}",
     "Negative skew warns that large losses are more likely than large gains of the same size.",
     "stats.skewness", "skew"),
    ("17", "returns", "Excess kurtosis", r"\text{Kurt} = \frac{\frac{1}{N}\sum (x_i - \bar{x})^4}{\left[\frac{1}{N}\sum (x_i - \bar{x})^2\right]^{2}} - 3",
     "Positive values mean fat tails: extreme moves happen more often than a normal curve predicts.",
     "stats.excess_kurtosis", "kurt"),
    ("18", "returns", "Standard error", r"SE(\bar{x}) = \frac{\sigma}{\sqrt{N}}",
     "How precisely the average return is known; it shrinks only with the square root of the sample size.",
     "stats.standard_error", "stderr_mean"),
    ("19", "returns", "Sharpe ratio", r"S = \frac{E[R] - R_f}{\sigma}",
     "Excess return earned per unit of total risk.",
     "stats.sharpe_ratio", "sharpe"),
    ("20", "returns", "Sortino ratio", r"\text{Sortino} = \frac{E[R] - T}{\sigma_D}, \quad \sigma_D = \sqrt{\tfrac{1}{N}\sum \min(0, R_i - T)^2}",
     "Like Sharpe but penalises only downside volatility, which is the risk investors dislike.",
     "stats.sortino_ratio", "sortino"),
    # ------------------------------------------------------------------ II
    ("21", "regression", "Linear regression model", r"y = X\beta + \varepsilon",
     "Explains an asset's return as a weighted sum of drivers plus unexplained noise.",
     "regression.linear_model", None),
    ("22", "regression", "OLS estimator", r"\hat{\beta} = (X^\top X)^{-1} X^\top y",
     "The coefficient estimates that minimise squared errors; the slope on the market is beta.",
     "regression.ols", "beta"),
    ("23", "regression", "Fitted values", r"\hat{y} = X\hat{\beta}",
     "The model's predicted values for each observation.",
     "regression.fitted_values", None),
    ("24", "regression", "Residuals", r"e = y - \hat{y}",
     "What the model fails to explain; for a factor model this is the idiosyncratic return.",
     "regression.residuals", None),
    ("25", "regression", "Sum of squared errors", r"SSE = \sum_{i=1}^{n}(y_i - \hat{y}_i)^2",
     "Total unexplained variation left after fitting the model.",
     "regression.sse", None),
    ("26", "regression", "Mean squared error", r"MSE = \frac{1}{n}\sum_{i=1}^{n}(y_i - \hat{y}_i)^2",
     "Average squared forecast miss, the usual yardstick for comparing models.",
     "regression.mse", None),
    ("27", "regression", "Root mean squared error", r"RMSE = \sqrt{MSE}",
     "Typical forecast error in the same units as the target.",
     "regression.rmse", None),
    ("28", "regression", "Mean absolute error", r"MAE = \frac{1}{n}\sum_{i=1}^{n}\lvert y_i - \hat{y}_i \rvert",
     "Average absolute forecast miss, less sensitive to a few large errors than RMSE.",
     "regression.mae", None),
    ("29", "regression", "R-squared", r"R^2 = 1 - \frac{SSE}{SST}, \quad SST = \sum (y_i - \bar{y})^2",
     "Share of an asset's variance explained by the model; against the market it measures systematic risk.",
     "regression.r_squared", "r2_mkt"),
    ("30", "regression", "Adjusted R-squared", r"\bar{R}^2 = 1 - (1 - R^2)\frac{n - 1}{n - k - 1}",
     "R-squared penalised for extra regressors, guarding against overfitting.",
     "regression.adjusted_r_squared", None),
    ("31", "regression", "t-statistic", r"t_j = \frac{\hat{\beta}_j - \beta_j^0}{SE(\hat{\beta}_j)}, \quad SE = \sqrt{\hat{\sigma}^2 [(X^\top X)^{-1}]_{jj}}",
     "Tests whether an estimate is distinguishable from zero; |t| above about 2 is conventionally significant.",
     "regression.t_statistic", "t_mean"),
    ("32", "regression", "Log-linear regression", r"\ln y = X\beta + \varepsilon",
     "Models percentage effects, useful when a driver changes a quantity proportionally.",
     "regression.log_linear_regression", None),
    ("33", "regression", "Interaction model", r"y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_1 x_2 + \varepsilon",
     "Lets the effect of one driver depend on the level of another, such as momentum only working in calm markets.",
     "regression.interaction_model", None),
    # ------------------------------------------------------------------ III
    ("34", "timeseries", "AR(p) model", r"x_t = c + \sum_{i=1}^{p}\phi_i x_{t-i} + \varepsilon_t",
     "Forecasts a series from its own recent past.",
     "timeseries.fit_ar", None),
    ("35", "timeseries", "AR(1) model", r"x_t = c + \phi x_{t-1} + \varepsilon_t",
     "Phi near 1 means shocks persist; well below 1 means the series snaps back to its mean.",
     "timeseries.fit_ar1", "ar1_phi"),
    ("36", "timeseries", "MA(q) model", r"x_t = \mu + \varepsilon_t + \sum_{j=1}^{q}\theta_j \varepsilon_{t-j}",
     "Captures short-lived effects of past shocks, such as bid-ask bounce.",
     "timeseries.fit_ma", None),
    ("37", "timeseries", "ARMA(p,q) model", r"x_t = c + \sum_{i=1}^{p}\phi_i x_{t-i} + \varepsilon_t + \sum_{j=1}^{q}\theta_j \varepsilon_{t-j}",
     "Combines persistence and shock memory in one compact forecasting model.",
     "timeseries.fit_arma", None),
    ("38", "timeseries", "First difference", r"\Delta x_t = x_t - x_{t-1}",
     "Turns a trending level such as a price into changes, which are usually stationary.",
     "timeseries.diff", None),
    ("39", "timeseries", "d-th difference", r"\Delta^d x_t = (1 - L)^d x_t",
     "Repeated differencing for series whose trend itself trends.",
     "timeseries.diff_n", None),
    ("40", "timeseries", "ARIMA(p,d,q) model", r"\phi(L)(1 - L)^d x_t = c + \theta(L)\varepsilon_t",
     "Differences a non-stationary series and then models it with ARMA.",
     "timeseries.fit_arima", None),
    ("41", "timeseries", "Autocorrelation", r"\rho_k = \frac{\operatorname{Cov}(x_t, x_{t-k})}{\operatorname{Var}(x_t)}",
     "Whether today's return tells you anything about tomorrow's; positive means trend, negative means reversal.",
     "timeseries.autocorrelation", "acf1"),
    ("42", "timeseries", "Weak stationarity", r"E[x_t] = \mu, \quad \operatorname{Var}(x_t) = \sigma^2, \quad \operatorname{Cov}(x_t, x_{t-k}) = \gamma_k",
     "Statistics estimated from the past only carry forward if mean, variance and autocovariance are stable.",
     "timeseries.stationarity_check", None),
    ("43", "timeseries", "Augmented Dickey-Fuller test", r"\Delta y_t = \alpha + \beta t + \gamma y_{t-1} + \sum_{i=1}^{k}\delta_i \Delta y_{t-i} + \varepsilon_t",
     "A t-stat on gamma below the critical value suggests the price mean-reverts rather than wanders.",
     "timeseries.adf_test", "adf_t"),
    # ------------------------------------------------------------------ IV
    ("44", "volatility", "EWMA variance", r"\sigma_t^2 = \lambda \sigma_{t-1}^2 + (1 - \lambda) r_{t-1}^2",
     "A volatility estimate that weights recent days most, reacting quickly to new turbulence.",
     "volatility.ewma_variance", "ewma_vol"),
    ("45", "volatility", "ARCH(q) model", r"\sigma_t^2 = \omega + \sum_{i=1}^{q}\alpha_i r_{t-i}^2",
     "Volatility rises after large moves: big shocks cluster together.",
     "volatility.arch_variance", None),
    ("46", "volatility", "GARCH(1,1) model", r"\sigma_t^2 = \omega + \alpha r_{t-1}^2 + \beta \sigma_{t-1}^2",
     "The workhorse volatility forecast; alpha plus beta near 1 means volatility shocks fade slowly.",
     "volatility.garch_fit", "garch_vol"),
    ("47", "volatility", "GJR-GARCH model", r"\sigma_t^2 = \omega + (\alpha + \gamma I_{t-1}) r_{t-1}^2 + \beta \sigma_{t-1}^2, \quad I_{t-1} = \mathbf{1}[r_{t-1} < 0]",
     "Captures the leverage effect: falls raise volatility more than rallies of the same size.",
     "volatility.gjr_garch_variance", None),
    ("48", "volatility", "Realized variance", r"RV_t = \sum_{i=1}^{n} r_{t,i}^2",
     "Variance measured directly from observed returns rather than from a model.",
     "volatility.realized_variance", None),
    ("49", "volatility", "Annualized realized volatility", r"\sigma_{ann} = \sqrt{A \cdot RV}",
     "Scales per-period variance to a yearly volatility figure for comparison across assets.",
     "volatility.realized_vol_annualized", "vol_ann"),
    ("50", "volatility", "Rolling beta", r"\beta_t = \frac{\operatorname{Cov}_t(R_i, R_m)}{\operatorname{Var}_t(R_m)}",
     "Tracks how an asset's market sensitivity drifts over time.",
     "volatility.rolling_beta", "beta"),
    # ------------------------------------------------------------------ V
    ("51", "stochastic", "Brownian increment", r"\Delta W_t = \sqrt{\Delta t}\, Z, \quad Z \sim N(0,1)",
     "The random shock that drives continuous-time price models; its size grows with the square root of time.",
     "stochastic.brownian_increment", None),
    ("52", "stochastic", "Brownian motion", r"W_{t+\Delta t} = W_t + \sqrt{\Delta t}\, Z_t",
     "A pure random walk in continuous time, the noise source for asset-price models.",
     "stochastic.brownian_path", None),
    ("53", "stochastic", "Geometric Brownian motion (Euler)", r"S_{t+\Delta t} = S_t + \mu S_t \Delta t + \sigma S_t \sqrt{\Delta t}\, Z",
     "The standard stock-price model used for simulation: drift plus proportional random shocks.",
     "stochastic.gbm_euler_step", None),
    ("54", "stochastic", "GBM exact solution", r"S_t = S_0 \exp\left[\left(\mu - \tfrac{1}{2}\sigma^2\right)t + \sigma W_t\right]",
     "Prices are log-normal, so the median outcome grows slower than the mean because of volatility drag.",
     "stochastic.gbm_exact", None),
    ("55", "stochastic", "Itô's lemma", r"df = \left(f_t + \mu f_x + \tfrac{1}{2}\sigma^2 f_{xx}\right)dt + \sigma f_x\, dW_t",
     "How the value of a derivative moves when its underlying follows a random process.",
     "stochastic.ito_lemma", None),
    ("56", "stochastic", "Ornstein-Uhlenbeck process", r"dX_t = \kappa(\theta - X_t)\,dt + \sigma\, dW_t",
     "A random process pulled back toward a long-run level, used for spreads, rates and pairs trades.",
     "stochastic.ou_path", None),
    ("57", "stochastic", "OU expected value", r"E[X_t] = \theta + (X_0 - \theta)e^{-\kappa t}",
     "The expected path of a mean-reverting series as it closes the gap to its long-run level.",
     "stochastic.ou_expected", None),
    ("58", "stochastic", "Mean-reversion half-life", r"t_{1/2} = \frac{\ln 2}{\kappa}, \quad \kappa = -\frac{\ln \phi}{\Delta t}",
     "How long it takes for half of a deviation from the mean to disappear, a guide to holding periods.",
     "stochastic.half_life", "half_life"),
    ("59", "stochastic", "Vasicek short rate", r"dr_t = a(b - r_t)\,dt + \sigma\, dW_t",
     "A mean-reverting interest-rate model with a closed-form bond price.",
     "stochastic.vasicek_path", None),
    ("60", "stochastic", "CIR short rate", r"dr_t = \kappa(\theta - r_t)\,dt + \sigma\sqrt{r_t}\, dW_t",
     "A rate model whose volatility shrinks near zero, keeping rates from going deeply negative.",
     "stochastic.cir_path", None),
    ("61", "stochastic", "Heston price process", r"dS_t = \mu S_t\, dt + \sqrt{v_t}\, S_t\, dW_t^{S}",
     "Stock price with volatility that itself moves randomly, producing fat tails and smiles.",
     "stochastic.heston_price_path", None),
    ("62", "stochastic", "Heston variance process", r"dv_t = \kappa(\theta - v_t)\,dt + \xi\sqrt{v_t}\, dW_t^{v}, \quad dW^S dW^v = \rho\, dt",
     "Variance mean-reverts and is usually negatively correlated with the price, as seen in equity markets.",
     "stochastic.heston_variance_path", None),
    # ------------------------------------------------------------------ VI
    ("63", "ml", "Parametric model", r"\hat{y} = f_\theta(x)",
     "Any forecasting model is a function of inputs with tunable parameters.",
     "ml.model_predict", None),
    ("64", "ml", "Empirical risk", r"\hat{R}(\theta) = \frac{1}{n}\sum_{i=1}^{n}\ell\big(y_i, f_\theta(x_i)\big)",
     "The average loss on historical data that training tries to minimise.",
     "ml.empirical_risk", None),
    ("65", "ml", "Regularized objective", r"\min_\theta \; \frac{1}{n}\sum_{i=1}^{n}\ell\big(y_i, f_\theta(x_i)\big) + \lambda\,\Omega(\theta)",
     "Adds a complexity penalty so a model does not simply memorise past noise.",
     "ml.regularized_objective", None),
    ("66", "ml", "Linear predictor", r"\hat{y} = w^\top x + b",
     "A weighted combination of signals, the simplest trading model.",
     "ml.linear_predictor", None),
    ("67", "ml", "Sigmoid", r"\sigma(z) = \frac{1}{1 + e^{-z}}",
     "Squashes any score into a probability between 0 and 1.",
     "ml.sigmoid", None),
    ("68", "ml", "Logistic regression", r"P(y = 1 \mid x) = \sigma(w^\top x + b)",
     "Estimates the probability of an event such as an up day or a default.",
     "ml.logistic_fit", None),
    ("69", "ml", "Binary cross-entropy", r"L = -\frac{1}{n}\sum_{i=1}^{n}\left[y_i \ln p_i + (1 - y_i)\ln(1 - p_i)\right]",
     "Scores probability forecasts, punishing confident wrong calls heavily.",
     "ml.binary_cross_entropy", None),
    ("70", "ml", "Softmax", r"p_k = \frac{e^{z_k}}{\sum_{j} e^{z_j}}",
     "Turns scores for several outcomes into probabilities that sum to one.",
     "ml.softmax", None),
    ("71", "ml", "Multiclass cross-entropy", r"L = -\sum_{k} y_k \ln p_k",
     "Scores a forecast across several possible regimes or ratings.",
     "ml.cross_entropy", None),
    ("72", "ml", "Hinge loss", r"\ell = \max\big(0,\, 1 - y f(x)\big), \quad y \in \{-1, +1\}",
     "The support-vector-machine loss, which only penalises wrong or low-margin calls.",
     "ml.hinge_loss", None),
    ("73", "ml", "Ridge regression", r"\hat{\beta} = (X^\top X + \lambda I)^{-1} X^\top y",
     "Shrinks coefficients toward zero, stabilising estimates when signals are correlated.",
     "ml.ridge", None),
    ("74", "ml", "LASSO", r"\min_\beta \; \frac{1}{2n}\lVert y - X\beta \rVert_2^2 + \lambda \lVert \beta \rVert_1",
     "Shrinks and switches off weak signals entirely, selecting a sparse set of factors.",
     "ml.lasso", None),
    ("75", "ml", "Elastic net", r"\min_\beta \; \frac{1}{2n}\lVert y - X\beta \rVert_2^2 + \lambda\left[\alpha\lVert \beta \rVert_1 + \tfrac{1 - \alpha}{2}\lVert \beta \rVert_2^2\right]",
     "Blends ridge and LASSO, selecting factors while handling groups of correlated signals.",
     "ml.elastic_net", None),
    ("76", "ml", "Regression-tree leaf prediction", r"\hat{y}_{R_m} = \frac{1}{\lvert R_m \rvert}\sum_{x_i \in R_m} y_i",
     "A tree predicts the average outcome of the historical cases that look like today.",
     "ml.tree_leaf_value", None),
    ("77", "ml", "Regression-tree split", r"\min_{j,s}\left[\sum_{x_i \in R_1(j,s)}(y_i - \bar{y}_{R_1})^2 + \sum_{x_i \in R_2(j,s)}(y_i - \bar{y}_{R_2})^2\right]",
     "Finds the single threshold on one signal that best separates good and bad outcomes.",
     "ml.best_split", None),
    ("78", "ml", "Random forest", r"\hat{f}(x) = \frac{1}{B}\sum_{b=1}^{B} T_b(x)",
     "Averages many trees built on resampled data to cut the noise of any single tree.",
     "ml.random_forest_fit", None),
    ("79", "ml", "Gradient boosting", r"F_m(x) = F_{m-1}(x) + \eta\, h_m(x)",
     "Builds a strong model by adding small trees that each fix the previous errors.",
     "ml.gradient_boosting_fit", None),
    ("80", "ml", "XGBoost objective", r"\mathcal{L} = \sum_{i}\ell(y_i, \hat{y}_i) + \sum_{k}\left(\gamma T_k + \tfrac{1}{2}\lambda \lVert w_k \rVert^2\right)",
     "Boosting with explicit penalties on tree size and leaf weights to limit overfitting.",
     "ml.xgb_objective", None),
    ("81", "ml", "k-means clustering", r"\min_{C}\sum_{k=1}^{K}\sum_{x_i \in C_k}\lVert x_i - \mu_k \rVert^2",
     "Groups assets or market days into clusters with similar behaviour.",
     "ml.kmeans", None),
    ("82", "ml", "PCA eigen-decomposition", r"\Sigma = V \Lambda V^\top",
     "Finds the few common factors, such as the market, that drive most co-movement.",
     "ml.pca", None),
    ("83", "ml", "PCA projection", r"z = V_k^\top (x - \mu)",
     "Expresses each observation in terms of those dominant factors.",
     "ml.pca_project", None),
    # ------------------------------------------------------------------ VII
    ("84", "nn", "Pre-activation", r"z = Wx + b",
     "Each neuron first forms a weighted sum of its inputs.",
     "nn.preactivation", None),
    ("85", "nn", "Activation functions", r"\text{ReLU}(z) = \max(0, z), \quad \tanh(z), \quad \sigma(z) = \frac{1}{1 + e^{-z}}",
     "Non-linear functions that let networks capture non-linear market relationships.",
     "nn.activation", None),
    ("86", "nn", "Two-layer network", r"\hat{y} = W_2\, \sigma(W_1 x + b_1) + b_2",
     "The simplest neural network: one hidden layer of learned features feeding a prediction.",
     "nn.two_layer_forward", None),
    ("87", "nn", "Deep layer", r"z^{(l)} = W^{(l)} a^{(l-1)} + b^{(l)}",
     "Each layer transforms the output of the layer before it.",
     "nn.deep_layer", None),
    ("88", "nn", "Layer activation", r"a^{(l)} = \sigma\big(z^{(l)}\big)",
     "The layer output after the non-linearity is applied.",
     "nn.layer_activation", None),
    ("89", "nn", "Chain rule", r"\frac{\partial L}{\partial \theta} = \frac{\partial L}{\partial \hat{y}}\cdot\frac{\partial \hat{y}}{\partial z}\cdot\frac{\partial z}{\partial \theta}",
     "Gradients of a composite model are products of the gradients of its pieces.",
     "nn.chain_rule", None),
    ("90", "nn", "Softmax cross-entropy gradient", r"\frac{\partial L}{\partial z} = \hat{y} - y",
     "The error signal for a classifier is simply predicted minus actual probabilities.",
     "nn.softmax_ce_grad", None),
    ("91", "nn", "Output-layer error", r"\delta^{(L)} = \nabla_{a} L \odot \sigma'\big(z^{(L)}\big)",
     "How much each output neuron contributed to the loss.",
     "nn.output_error", None),
    ("92", "nn", "Hidden-layer backpropagation", r"\delta^{(l)} = \big(W^{(l+1)}\big)^\top \delta^{(l+1)} \odot \sigma'\big(z^{(l)}\big)",
     "Passes blame for the error backward through the network.",
     "nn.hidden_delta", None),
    ("93", "nn", "Weight gradient", r"\frac{\partial L}{\partial W^{(l)}} = \delta^{(l)} \big(a^{(l-1)}\big)^\top",
     "The direction to adjust each weight to reduce the loss.",
     "nn.weight_gradient", None),
    ("94", "nn", "Bias gradient", r"\frac{\partial L}{\partial b^{(l)}} = \delta^{(l)}",
     "The direction to adjust each bias to reduce the loss.",
     "nn.bias_gradient", None),
    ("95", "nn", "Gradient descent", r"\theta \leftarrow \theta - \eta \nabla_\theta L(\theta)",
     "Moves parameters a small step downhill on the loss surface.",
     "nn.gd_step", None),
    ("96", "nn", "Stochastic gradient descent", r"\theta \leftarrow \theta - \eta \nabla_\theta L_{B}(\theta)",
     "Uses a random mini-batch of data for each step, trading precision for speed.",
     "nn.sgd_step", None),
    ("97", "nn", "Momentum", r"v_t = \beta v_{t-1} + \nabla_\theta L, \quad \theta \leftarrow \theta - \eta v_t",
     "Accumulates past gradients to move faster through flat regions and damp oscillation.",
     "nn.momentum_step", None),
    ("98", "nn", "Adam first moment", r"m_t = \beta_1 m_{t-1} + (1 - \beta_1) g_t",
     "A running average of gradients, the direction estimate in Adam.",
     "nn.adam_first_moment", None),
    ("99", "nn", "Adam second moment", r"v_t = \beta_2 v_{t-1} + (1 - \beta_2) g_t^2",
     "A running average of squared gradients, used to scale each step.",
     "nn.adam_second_moment", None),
    ("100", "nn", "Adam update", r"\hat{m}_t = \frac{m_t}{1 - \beta_1^t}, \quad \hat{v}_t = \frac{v_t}{1 - \beta_2^t}, \quad \theta \leftarrow \theta - \eta\frac{\hat{m}_t}{\sqrt{\hat{v}_t} + \epsilon}",
     "An adaptive step size per parameter, the default optimiser for training networks.",
     "nn.adam_update", None),
    # ------------------------------------------------------------------ VIII
    ("101", "portfolio", "Mean-variance optimization", r"\max_w \; w^\top \mu - \frac{\lambda}{2} w^\top \Sigma w \;\Rightarrow\; w^* = \frac{1}{\lambda}\Sigma^{-1}\mu",
     "Equation 101: mean-variance optimization — the weights that best trade expected return against variance for a given risk aversion.",
     "portfolio.mean_variance_weights", None),
    ("102", "portfolio", "Fully invested constraint", r"\sum_{i=1}^{n} w_i = \mathbf{1}^\top w = 1",
     "All capital is allocated: weights sum to 100%.",
     "portfolio.is_fully_invested", None),
    ("103", "portfolio", "Target-return frontier", r"\min_w \; w^\top \Sigma w \;\; \text{s.t.} \;\; w^\top \mu = m, \; \mathbf{1}^\top w = 1",
     "The lowest-risk portfolio that achieves a chosen expected return; tracing m gives the efficient frontier.",
     "portfolio.frontier_weights", None),
    ("104", "portfolio", "Global minimum-variance portfolio", r"w_{GMV} = \frac{\Sigma^{-1}\mathbf{1}}{\mathbf{1}^\top \Sigma^{-1}\mathbf{1}}",
     "The least volatile fully invested portfolio, needing no return forecasts at all.",
     "portfolio.gmv_weights", None),
    ("105", "portfolio", "Risk contributions", r"RC_i = \frac{w_i (\Sigma w)_i}{\sigma_p}, \quad \sum_i RC_i = \sigma_p",
     "Shows which positions actually drive portfolio risk, which can differ sharply from their weights.",
     "portfolio.risk_contributions", None),
    ("106", "portfolio", "Market beta", r"\beta_i = \frac{\operatorname{Cov}(R_i, R_m)}{\operatorname{Var}(R_m)}",
     "Sensitivity to the market: a beta of 1.5 tends to move 1.5% for each 1% market move.",
     "portfolio.market_beta", "beta"),
    ("107", "portfolio", "CAPM expected return", r"E[R_i] = R_f + \beta_i\big(E[R_m] - R_f\big)",
     "The return an asset should earn for its market risk alone.",
     "portfolio.capm_expected_return", "capm_er"),
    ("108", "portfolio", "Jensen's alpha", r"\alpha = R_p - \left[R_f + \beta_p (R_m - R_f)\right]",
     "Return earned above what market exposure alone would have delivered.",
     "portfolio.jensens_alpha", "alpha_ann"),
    ("109", "portfolio", "Parametric VaR", r"\text{VaR}_\alpha = \mu_L + z_\alpha \sigma_L",
     "A loss level that should be exceeded only (1 - alpha) of the time if returns are normal.",
     "portfolio.parametric_var", "var_95"),
    ("110", "portfolio", "Expected shortfall", r"\text{ES}_\alpha = \mu_L + \sigma_L \frac{\varphi(z_\alpha)}{1 - \alpha}",
     "The average loss on the days that breach VaR, a better measure of tail risk.",
     "portfolio.expected_shortfall", "es_95"),
    # ------------------------------------------------------------------ IX
    ("111", "fixed_income", "Bond price", r"P = \sum_{t=1}^{T}\frac{CF_t}{(1 + y)^t}",
     "A bond is worth the present value of its coupons and principal.",
     "fixed_income.bond_price_cf", None),
    ("112", "fixed_income", "Yield to maturity", r"P = \sum_{t=1}^{T}\frac{CF_t}{(1 + y)^t} \;\text{ solved for } y",
     "The single discount rate that equates price and cash flows; the bond's promised return.",
     "fixed_income.ytm", None),
    ("113", "fixed_income", "Macaulay duration", r"D_{Mac} = \frac{1}{P}\sum_{t=1}^{T} t \cdot \frac{CF_t}{(1 + y)^t}",
     "The weighted-average time to receive a bond's cash flows.",
     "fixed_income.macaulay_duration", None),
    ("114", "fixed_income", "Modified duration", r"D_{mod} = \frac{D_{Mac}}{1 + y/m}",
     "Approximate percentage price fall for a one-point rise in yield.",
     "fixed_income.modified_duration", None),
    ("115", "fixed_income", "Convexity", r"C = \frac{1}{P}\frac{\partial^2 P}{\partial y^2}, \quad \frac{\Delta P}{P} \approx -D_{mod}\,\Delta y + \tfrac{1}{2} C (\Delta y)^2",
     "The curvature that makes bond prices rise more than they fall for equal yield moves.",
     "fixed_income.convexity", None),
    ("116", "fixed_income", "DV01", r"DV01 = D_{mod} \times P \times 0.0001",
     "Dollar value change for a one-basis-point move in yield, the unit for sizing rate hedges.",
     "fixed_income.dv01", None),
    ("117", "fixed_income", "Zero-coupon price", r"P(0,T) = \frac{1}{(1 + y)^T} \quad\text{or}\quad P(0,T) = e^{-yT}",
     "Today's price of one unit paid at a single future date, the discount factor.",
     "fixed_income.zero_coupon_price", None),
    ("118", "fixed_income", "Forward rate", r"f(T_1, T_2) = \frac{r_2 T_2 - r_1 T_1}{T_2 - T_1}",
     "The borrowing rate between two future dates that is locked in by today's curve.",
     "fixed_income.forward_rate", None),
    # ------------------------------------------------------------------ X
    ("D1", "forwards", "Forward price", r"F_0 = S_0 e^{rT}",
     "Fair forward price of an asset with no income: spot plus the cost of financing it.",
     "derivatives.forward_price", None),
    ("D2", "forwards", "Forward price with dividend yield", r"F_0 = S_0 e^{(r - q)T}",
     "Dividends received while holding the asset reduce the fair forward price.",
     "derivatives.forward_price_dividend", None),
    ("D3", "forwards", "FX forward", r"F_0 = S_0 e^{(r_d - r_f)T}",
     "Covered interest parity: the higher-rate currency trades at a forward discount.",
     "derivatives.fx_forward", None),
    ("D4", "forwards", "Commodity cost of carry", r"F_0 = S_0 e^{(r + c - y)T}",
     "Storage costs raise and convenience yield lowers the fair commodity forward price.",
     "derivatives.commodity_forward", None),
    ("D5", "forwards", "Long futures P&L", r"\text{P\&L}_{long} = N \cdot M \cdot (F_t - F_0)",
     "Gain on a long futures position from the price change times contract size.",
     "derivatives.futures_pnl_long", None),
    ("D6", "forwards", "Short futures P&L", r"\text{P\&L}_{short} = N \cdot M \cdot (F_0 - F_t)",
     "A short futures position gains when the futures price falls.",
     "derivatives.futures_pnl_short", None),
    # ------------------------------------------------------------------ XI
    ("D7", "options", "Long call payoff and profit", r"\text{Payoff} = \max(S_T - K, 0), \quad \text{Profit} = \max(S_T - K, 0) - C_0",
     "A call gains from a rise above the strike and can lose no more than the premium paid.",
     "derivatives.long_call", None),
    ("D8", "options", "Long put payoff and profit", r"\text{Payoff} = \max(K - S_T, 0), \quad \text{Profit} = \max(K - S_T, 0) - P_0",
     "A put gains from a fall below the strike, working as insurance on a holding.",
     "derivatives.long_put", None),
    ("D9", "options", "Put-call parity", r"C - P = S_0 e^{-qT} - PV(D) - K e^{-rT}",
     "Links call and put prices; a gap signals mispricing or an arbitrage opportunity.",
     "derivatives.parity_gap", None),
    ("D10", "options", "Black-Scholes-Merton call", r"C = S_0 e^{-qT} N(d_1) - K e^{-rT} N(d_2)",
     "The benchmark fair value of a European call option.",
     "derivatives.bsm_call", None),
    ("D11", "options", "Black-Scholes-Merton put", r"P = K e^{-rT} N(-d_2) - S_0 e^{-qT} N(-d_1)",
     "The benchmark fair value of a European put option.",
     "derivatives.bsm_put", None),
    ("D12", "options", "d1 and d2", r"d_1 = \frac{\ln(S_0/K) + (r - q + \tfrac{1}{2}\sigma^2)T}{\sigma\sqrt{T}}, \quad d_2 = d_1 - \sigma\sqrt{T}",
     "Standardised moneyness; N(d2) is the risk-neutral chance the option finishes in the money.",
     "derivatives.d1_d2", None),
    ("D13", "options", "Call delta", r"\Delta_C = e^{-qT} N(d_1)",
     "Shares of stock needed to hedge one call, and its sensitivity to the stock price.",
     "derivatives.call_delta", None),
    ("D14", "options", "Put delta", r"\Delta_P = e^{-qT}\big(N(d_1) - 1\big)",
     "A put's (negative) sensitivity to the stock price.",
     "derivatives.put_delta", None),
    ("D15", "options", "Gamma", r"\Gamma = \frac{e^{-qT}\varphi(d_1)}{S_0 \sigma \sqrt{T}}",
     "How fast delta changes; high gamma means hedges need frequent rebalancing.",
     "derivatives.gamma", None),
    ("D16", "options", "Vega", r"\mathcal{V} = S_0 e^{-qT}\varphi(d_1)\sqrt{T}",
     "Value change for a one-point change in implied volatility.",
     "derivatives.vega", None),
    ("D17", "options", "Call rho", r"\rho_C = K T e^{-rT} N(d_2)",
     "Call value sensitivity to interest rates.",
     "derivatives.call_rho", None),
    ("D18", "options", "Put rho", r"\rho_P = -K T e^{-rT} N(-d_2)",
     "Put value sensitivity to interest rates.",
     "derivatives.put_rho", None),
    ("D19", "options", "Theta", r"\Theta_C = -\frac{S_0 e^{-qT}\varphi(d_1)\sigma}{2\sqrt{T}} - rKe^{-rT}N(d_2) + qS_0e^{-qT}N(d_1)",
     "Value lost per year as time passes with everything else unchanged.",
     "derivatives.theta", None),
    ("D20", "options", "Implied volatility", r"C_{BSM}(\sigma_{imp}) = C_{market}",
     "The volatility the market is pricing in, backed out from an option's price.",
     "derivatives.implied_vol", None),
    # ------------------------------------------------------------------ XII
    ("S1", "swaps", "Swap value", r"PV_{swap} = PV_{receive} - PV_{pay}",
     "A swap is worth the value of the leg received minus the leg paid.",
     "swaps.swap_pv", None),
    ("S2", "swaps", "Fixed leg PV", r"PV_{fixed} = N \cdot K \sum_{i=1}^{n}\alpha_i DF_i",
     "Present value of the fixed coupons on a swap.",
     "swaps.fixed_leg_pv", None),
    ("S3", "swaps", "Floating leg PV", r"PV_{float} = N \sum_{i=1}^{n} L_i \alpha_i DF_i",
     "Present value of the floating payments projected from forward rates.",
     "swaps.floating_leg_pv", None),
    ("S4", "swaps", "Interest-rate swap PV", r"PV_{IRS} = N \sum_{i=1}^{n}(L_i - K)\alpha_i DF_i",
     "Value to the fixed payer: positive when expected floating rates exceed the fixed rate.",
     "swaps.irs_pv", None),
    ("S5", "swaps", "Par swap rate", r"K^* = \frac{\sum_{i} L_i \alpha_i DF_i}{\sum_{i}\alpha_i DF_i}",
     "The fixed rate that makes a new swap worth zero, the quoted swap rate.",
     "swaps.par_swap_rate", None),
    ("S6", "swaps", "TRS total return", r"TR = \frac{S_t - S_0 + D_t}{S_0}",
     "The price gain plus dividends passed through a total return swap.",
     "swaps.trs_total_return", None),
    ("S7", "swaps", "TRS equity-leg cash flow", r"CF_{equity} = N \cdot TR",
     "Cash paid to the total-return receiver, positive or negative.",
     "swaps.trs_equity_leg", None),
    ("S8", "swaps", "TRS financing leg", r"CF_{fin} = N\,(r_{ref} + s)\,\Delta t",
     "The funding cost the total-return receiver pays for synthetic exposure.",
     "swaps.trs_financing_leg", None),
    ("S9", "swaps", "TRS net cash flow", r"CF_{net} = N \cdot TR - N\,(r_{ref} + s)\,\Delta t",
     "Net result for the receiver: asset performance minus financing.",
     "swaps.trs_net_cash_flow", None),
    # ------------------------------------------------------------------ XIII
    ("C1", "credit", "Loss given default", r"LGD = 1 - R",
     "The share of exposure lost if the borrower defaults.",
     "credit.loss_given_default", None),
    ("C2", "credit", "Expected loss", r"EL = PD \times LGD \times EAD",
     "The average credit loss to reserve for on an exposure.",
     "credit.expected_loss", None),
    ("C3", "credit", "Survival probability", r"Q(t) = e^{-\lambda t}",
     "Chance the borrower has not defaulted by time t under a constant hazard rate.",
     "credit.survival_probability", None),
    ("C4", "credit", "Default probability", r"PD(t) = 1 - e^{-\lambda t}",
     "Cumulative chance of default by time t.",
     "credit.default_probability", None),
    ("C5", "credit", "Credit triangle", r"s \approx \lambda (1 - R)",
     "Rule of thumb linking spread, default intensity and recovery.",
     "credit.credit_triangle_spread", None),
    ("C6", "credit", "CDS protection leg PV", r"PV_{prot} = N (1 - R)\sum_{i=1}^{n} DF_i\,\big(Q_{i-1} - Q_i\big)",
     "Present value of the default payout the protection buyer expects to receive.",
     "credit.cds_protection_leg_pv", None),
    ("C7", "credit", "CDS premium leg PV", r"PV_{prem} = N \cdot s \sum_{i=1}^{n}\alpha_i DF_i Q_i",
     "Present value of the spread payments made while the name survives.",
     "credit.cds_premium_leg_pv", None),
    ("C8", "credit", "Par CDS spread", r"\boxed{s^* = \frac{(1 - R)\sum_{i=1}^{n} DF_i\,(Q_{i-1} - Q_i)}{\sum_{i=1}^{n}\alpha_i DF_i Q_i}}",
     "The spread that makes protection and premium legs equal, the market's price of default risk.",
     "credit.par_cds_spread", None),
    ("C9", "credit", "Hazard-rate bootstrap", r"\text{find } \lambda : \; s^*(\lambda) = s_{market}",
     "Backs out the default intensity the market is implying from a quoted spread.",
     "credit.bootstrap_flat_hazard", None),
]

EQUATIONS = [
    {"id": i, "section": s, "name": n, "latex": l, "note": note, "fn": _P + fn, "metric": m}
    for (i, s, n, l, note, fn, m) in _ROWS
]


def catalog():
    """The full library as JSON-able data: {"sections": [...], "equations": [...]}."""
    return {
        "sections": [{"key": k, "title": t} for k, t in SECTIONS],
        "equations": [dict(e) for e in EQUATIONS],
    }


def resolve(fn_path):
    """Import and return the function named by a dotted path such as 'finsim.quant.stats.mean'."""
    import importlib
    mod, _, name = fn_path.rpartition(".")
    return getattr(importlib.import_module(mod), name)


def source(fn_path):
    """Python source code of an equation's implementing function."""
    import inspect
    return inspect.getsource(resolve(fn_path))
