"""The vertical-slice walkthrough (spec §46), runnable from the CLI.

It drives the same commands the UI uses and prints what happened at each step,
including the accounting entries and the causal audit trail for the buy.
"""
from __future__ import annotations

from datetime import date
from decimal import Decimal

from .domain.events import E
from .engines.ledger import account_name
from .money import D
from .store import EventStore
from .world import World


def _p(title: str) -> None:
    print("\n" + "=" * 78 + f"\n{title}\n" + "=" * 78)


def _entries(w: World, pid: str, since_seq: int) -> None:
    led = w.ledgers[pid]
    for e in led.entries:
        if int(e.event_id[3:]) <= since_seq:
            continue
        print(f"  {e.id}  {e.date}  {e.memo}   [cause {e.cause_id}]")
        for l in e.lines:
            side = f"Dr {l.debit:>14,.2f}" if l.debit else f"{'':17}Cr {l.credit:>14,.2f}"
            print(f"      {l.account:<9} {account_name(l.account):<44} {side}   {l.security_id or ''}")


def run_demo(seed: int = 42, start: str = "2026-01-05") -> World:
    store = EventStore(":memory:")
    w = World.create("demo", "Vertical slice", seed, date.fromisoformat(start), store=store)
    _p("1. Start with $10,000,000")
    pf = w.create_portfolio("Demo Portfolio", "PERSONAL", D(10_000_000))
    pid = pf.id
    print(f"  portfolio {pid}  cash USD {pf.cash['USD'].balance:,.2f}  NAV {w.ledgers[pid].nav():,.2f}  date {w.current_date}")

    _p("2. View the simulated market")
    # choose a dividend payer with the nearest upcoming ex-date so the slice shows a dividend quickly
    cas = sorted((ca for ca in w.corporate_actions.values() if ca.status == "DECLARED"), key=lambda c: c.ex_date)
    ca = cas[0]
    tkr = ca.security_id
    for t in list(w.securities)[:8]:
        b = w.market.last_bar(t)
        print(f"  {t:<7} last {b.close:>10}  bid {b.bid:>10}  ask {b.ask:>10}  vol {b.volume:>12,}")
    print(f"  ... {len(w.securities)} securities. Regime: {w.market.regime().label}. Nearest dividend: {tkr} ex {ca.ex_date} pay {ca.pay_date} ${ca.amount_per_unit}/sh")

    _p(f"3-4. Buy 10,000 {tkr} — see the trade execute")
    seq0 = len(w.events)
    o = w.place_order(pid, tkr, "BUY", 10000)
    t = pf.trades[o.trade_ids[0]]
    ed = t.execution_detail
    print(f"  order {o.id} {o.status}; trade {t.id} {t.side} {t.quantity:,} @ {t.price} (ref ask {ed['reference_ask']}, impact {ed['impact_bps']}bp, "
          f"spread cost {ed['spread_cost']}, impact cost {ed['impact_cost']})\n  gross {t.gross_amount:,.2f} + commission {t.commission:,.2f} = net {t.net_amount:,.2f} "
          f"payable; trade date {t.trade_date}, settles {t.settlement_date}; status {t.status}")
    print("  accounting entries generated by the trade:")
    _entries(w, pid, seq0)

    _p("5. Settlement obligation")
    si = pf.settlements[t.settlement_instruction_id]
    print(f"  {si.id} {si.instruction_type} {si.quantity:,} {si.security_id} vs {si.currency} {si.cash_amount:,.2f} on {si.settlement_date}; "
          f"{si.delivering_party} -> {si.receiving_party} at {si.custodian}; status {si.status}")
    pos = pf.positions[tkr]
    print(f"  position: trade-date qty {pos.quantity:,}, settled {pos.settled_quantity:,}, pending receive {pos.pending_receive:,}")
    print(f"  cash: settled {pf.cash['USD'].balance:,.2f}, projected {w.trading.projected_cash(pf, 'USD'):,.2f}")

    _p("6-9. Advance time: securities settle into custody, cash leaves, position appears")
    seq1 = len(w.events)
    w.advance(1)
    while t.status != "SETTLED":
        w.advance(1)
    print(f"  date {w.current_date}; trade {t.id} status {t.status}: " + " -> ".join(h['status'] for h in t.status_history))
    print(f"  instruction {si.id}: {si.status} on {si.settled_date}")
    print(f"  custody: settled qty {pos.settled_quantity:,}; cash movements: " + "; ".join(f"{m.kind} {m.amount:,.2f}" for m in pf.cash_movements))
    print(f"  cash settled {pf.cash['USD'].balance:,.2f}")
    print("  settlement entries:")
    _entries(w, pid, seq1)

    _p("10-11. Prices move, unrealized P&L updates")
    for s in pf.nav_history:
        print(f"  {s.date} NAV {s.nav:,.2f}  day P&L {s.day_pnl:>+12,.2f}  explain: " + ", ".join(f"{k} {v:+,.2f}" for k, v in s.explain.items() if not k.startswith('_') and v))
    print(f"  {tkr}: mark {pos.mark}, MV {pos.market_value:,.2f}, cost {pos.cost_basis:,.2f}, unrealized {pos.unrealized_pnl:+,.2f}")

    _p("12-13. Receive the dividend")
    while ca.status != "PAID":
        w.advance(1)
    ent = ca.entitlements[pid]
    print(f"  {ca.id}: ex {ca.ex_date} entitled {ent['quantity']:,} x {ca.amount_per_unit} = {ent['amount']:,.2f}; paid {ca.pay_date}")
    divs = [m for m in pf.cash_movements if m.kind == "DIVIDEND"]
    print(f"  cash movement: {divs[0].date} {divs[0].kind} {divs[0].amount:+,.2f} -> balance {divs[0].balance_after:,.2f}")
    ent_ev = next(e for e in w.events if e.type == E.DIVIDEND_ENTITLED and e.payload["ca_id"] == ca.id)
    paid_ev = next(e for e in w.events if e.type == E.DIVIDEND_PAID and e.payload["ca_id"] == ca.id)
    for ev in (ent_ev, paid_ev):
        for cid in w.children.get(ev.id, []):
            c = w.events_by_id[cid]
            if c.type == E.LEDGER_POSTED:
                e = w.ledgers[pid].entries_by_id[c.payload["entry_id"]]
                print(f"  {e.id} {e.date} {e.memo}")
                for l in e.lines:
                    print(f"      {l.account:<9} {account_name(l.account):<40} " + (f"Dr {l.debit:,.2f}" if l.debit else f"   Cr {l.credit:,.2f}"))

    _p("14-15. Sell 4,000 shares — realized P&L")
    seq2 = len(w.events)
    o2 = w.place_order(pid, tkr, "SELL", 4000)
    t2 = pf.trades[o2.trade_ids[0]]
    print(f"  {t2.id} SELL {t2.quantity:,} @ {t2.price}; proceeds {t2.gross_amount:,.2f} - commission {t2.commission:,.2f} = {t2.net_amount:,.2f}")
    print(f"  lots relieved: " + "; ".join(f"{l['lot_id']} {l['quantity']:,} @ {l['cost_per_unit']}" for l in t2.lots_relieved))
    print(f"  realized P&L {t2.realized_pnl:+,.2f}; position now {pos.quantity:,} (settled {pos.settled_quantity:,}, pending deliver {pos.pending_deliver:,})")
    _p("16. Every resulting accounting entry")
    _entries(w, pid, seq2)
    w.advance(2)
    print(f"\n  after settlement: cash {pf.cash['USD'].balance:,.2f}; {t2.id} {t2.status}; settled qty {pos.settled_quantity:,}")

    _p("17. Audit trail — causal chain of the original buy")
    ev = next(e for e in w.events if e.type == E.TRADE_EXECUTED and e.payload["trade_id"] == t.id)
    chain = w.audit_chain(ev.id)
    print("  ancestors: " + " -> ".join(f"{a.id} {a.type}" for a in chain["ancestors"]))
    def show(node, depth=0):
        e = node["event"]
        print("  " + "    " * depth + f"{e.id} {e.type} " + (e.payload.get("memo") or e.payload.get("si_id") or e.payload.get("status") or ""))
        for c in node["children"]:
            show(c, depth + 1)
    show(chain["tree"])
    led = w.ledgers[pid]
    tb = led.trial_balance()
    summ = w.pnl.compute_summary(pf)
    print(f"\n  events: {len(w.events)}; ledger entries: {len(led.entries)}; trial balance balanced: {tb['balanced']}; "
          f"ledger NAV {led.nav():,.2f} == economic NAV {summ['nav']:,.2f}: {led.nav() == summ['nav']}")
    # replay proof
    w2 = World.load(store, "demo")
    print(f"  replay from event store: NAV {w2.ledgers[pid].nav():,.2f}, events {len(w2.events)}, identical: {w2.ledgers[pid].nav() == led.nav() and len(w2.events) == len(w.events)}")
    return w


if __name__ == "__main__":
    run_demo()
