"""The names the universe snapshot is built from (tools/refresh_universe.py reads this).

Row: (ticker, name, asset class, GICS sector, country[, Yahoo symbol when it differs from the ticker]).
Asset classes: EQUITY, ADR, REIT, PREFERRED, ETF, CRYPTO. Tickers that Yahoo cannot price are skipped by the refresh,
so a delisted or renamed name simply drops out of the snapshot. Bonds are representative senior unsecured issues
(and USD sovereigns) with a coupon, years to maturity, an S&P-style rating and a spread over Treasuries.
"""

STOCKS = [
    # ---- Information Technology
    ("AAPL", "Apple Inc.", "EQUITY", "Information Technology", "US"),
    ("MSFT", "Microsoft Corporation", "EQUITY", "Information Technology", "US"),
    ("NVDA", "NVIDIA Corporation", "EQUITY", "Information Technology", "US"),
    ("AVGO", "Broadcom Inc.", "EQUITY", "Information Technology", "US"),
    ("ORCL", "Oracle Corporation", "EQUITY", "Information Technology", "US"),
    ("CRM", "Salesforce, Inc.", "EQUITY", "Information Technology", "US"),
    ("AMD", "Advanced Micro Devices, Inc.", "EQUITY", "Information Technology", "US"),
    ("INTC", "Intel Corporation", "EQUITY", "Information Technology", "US"),
    ("ADBE", "Adobe Inc.", "EQUITY", "Information Technology", "US"),
    ("CSCO", "Cisco Systems, Inc.", "EQUITY", "Information Technology", "US"),
    ("IBM", "International Business Machines Corporation", "EQUITY", "Information Technology", "US"),
    ("QCOM", "QUALCOMM Incorporated", "EQUITY", "Information Technology", "US"),
    ("TXN", "Texas Instruments Incorporated", "EQUITY", "Information Technology", "US"),
    ("AMAT", "Applied Materials, Inc.", "EQUITY", "Information Technology", "US"),
    ("MU", "Micron Technology, Inc.", "EQUITY", "Information Technology", "US"),
    ("NOW", "ServiceNow, Inc.", "EQUITY", "Information Technology", "US"),
    ("INTU", "Intuit Inc.", "EQUITY", "Information Technology", "US"),
    ("PANW", "Palo Alto Networks, Inc.", "EQUITY", "Information Technology", "US"),
    ("ANET", "Arista Networks, Inc.", "EQUITY", "Information Technology", "US"),
    ("PLTR", "Palantir Technologies Inc.", "EQUITY", "Information Technology", "US"),
    ("SNOW", "Snowflake Inc.", "EQUITY", "Information Technology", "US"),
    ("SHOP", "Shopify Inc.", "EQUITY", "Information Technology", "CA"),
    ("ACN", "Accenture plc", "EQUITY", "Information Technology", "IE"),
    ("ADI", "Analog Devices, Inc.", "EQUITY", "Information Technology", "US"),
    ("LRCX", "Lam Research Corporation", "EQUITY", "Information Technology", "US"),
    ("KLAC", "KLA Corporation", "EQUITY", "Information Technology", "US"),
    ("SNPS", "Synopsys, Inc.", "EQUITY", "Information Technology", "US"),
    ("CDNS", "Cadence Design Systems, Inc.", "EQUITY", "Information Technology", "US"),
    ("CRWD", "CrowdStrike Holdings, Inc.", "EQUITY", "Information Technology", "US"),
    ("FTNT", "Fortinet, Inc.", "EQUITY", "Information Technology", "US"),
    ("MRVL", "Marvell Technology, Inc.", "EQUITY", "Information Technology", "US"),
    ("NXPI", "NXP Semiconductors N.V.", "EQUITY", "Information Technology", "NL"),
    ("MCHP", "Microchip Technology Incorporated", "EQUITY", "Information Technology", "US"),
    ("ADSK", "Autodesk, Inc.", "EQUITY", "Information Technology", "US"),
    ("WDAY", "Workday, Inc.", "EQUITY", "Information Technology", "US"),
    ("DDOG", "Datadog, Inc.", "EQUITY", "Information Technology", "US"),
    ("ZS", "Zscaler, Inc.", "EQUITY", "Information Technology", "US"),
    ("NET", "Cloudflare, Inc.", "EQUITY", "Information Technology", "US"),
    ("TEAM", "Atlassian Corporation", "EQUITY", "Information Technology", "AU"),
    ("MDB", "MongoDB, Inc.", "EQUITY", "Information Technology", "US"),
    ("HUBS", "HubSpot, Inc.", "EQUITY", "Information Technology", "US"),
    ("APH", "Amphenol Corporation", "EQUITY", "Information Technology", "US"),
    ("GLW", "Corning Incorporated", "EQUITY", "Information Technology", "US"),
    ("TEL", "TE Connectivity plc", "EQUITY", "Information Technology", "IE"),
    ("HPQ", "HP Inc.", "EQUITY", "Information Technology", "US"),
    ("HPE", "Hewlett Packard Enterprise Company", "EQUITY", "Information Technology", "US"),
    ("DELL", "Dell Technologies Inc.", "EQUITY", "Information Technology", "US"),
    ("SMCI", "Super Micro Computer, Inc.", "EQUITY", "Information Technology", "US"),
    ("STX", "Seagate Technology Holdings plc", "EQUITY", "Information Technology", "IE"),
    ("WDC", "Western Digital Corporation", "EQUITY", "Information Technology", "US"),
    ("KEYS", "Keysight Technologies, Inc.", "EQUITY", "Information Technology", "US"),
    ("FSLR", "First Solar, Inc.", "EQUITY", "Information Technology", "US"),
    ("ENPH", "Enphase Energy, Inc.", "EQUITY", "Information Technology", "US"),
    ("ON", "ON Semiconductor Corporation", "EQUITY", "Information Technology", "US"),
    ("MPWR", "Monolithic Power Systems, Inc.", "EQUITY", "Information Technology", "US"),
    ("CTSH", "Cognizant Technology Solutions Corporation", "EQUITY", "Information Technology", "US"),
    ("IT", "Gartner, Inc.", "EQUITY", "Information Technology", "US"),
    ("GDDY", "GoDaddy Inc.", "EQUITY", "Information Technology", "US"),
    ("AKAM", "Akamai Technologies, Inc.", "EQUITY", "Information Technology", "US"),
    ("FFIV", "F5, Inc.", "EQUITY", "Information Technology", "US"),
    ("ZBRA", "Zebra Technologies Corporation", "EQUITY", "Information Technology", "US"),
    ("TER", "Teradyne, Inc.", "EQUITY", "Information Technology", "US"),
    ("TYL", "Tyler Technologies, Inc.", "EQUITY", "Information Technology", "US"),
    ("FICO", "Fair Isaac Corporation", "EQUITY", "Information Technology", "US"),
    ("PAYC", "Paycom Software, Inc.", "EQUITY", "Information Technology", "US"),
    ("OKTA", "Okta, Inc.", "EQUITY", "Information Technology", "US"),
    ("DOCU", "DocuSign, Inc.", "EQUITY", "Information Technology", "US"),
    ("TWLO", "Twilio Inc.", "EQUITY", "Information Technology", "US"),
    ("PATH", "UiPath Inc.", "EQUITY", "Information Technology", "US"),
    ("APP", "AppLovin Corporation", "EQUITY", "Information Technology", "US"),
    ("MSTR", "Strategy Inc.", "EQUITY", "Information Technology", "US"),
    ("XYZ", "Block, Inc.", "EQUITY", "Financials", "US"),
    ("U", "Unity Software Inc.", "EQUITY", "Information Technology", "US"),
    ("GFS", "GlobalFoundries Inc.", "EQUITY", "Information Technology", "US"),
    ("SWKS", "Skyworks Solutions, Inc.", "EQUITY", "Information Technology", "US"),
    ("QRVO", "Qorvo, Inc.", "EQUITY", "Information Technology", "US"),
    ("ENTG", "Entegris, Inc.", "EQUITY", "Information Technology", "US"),
    ("COHR", "Coherent Corp.", "EQUITY", "Information Technology", "US"),
    ("JBL", "Jabil Inc.", "EQUITY", "Information Technology", "US"),
    ("NTAP", "NetApp, Inc.", "EQUITY", "Information Technology", "US"),
    ("PSTG", "Pure Storage, Inc.", "EQUITY", "Information Technology", "US"),
    ("CDW", "CDW Corporation", "EQUITY", "Information Technology", "US"),
    ("EPAM", "EPAM Systems, Inc.", "EQUITY", "Information Technology", "US"),
    ("VRSN", "VeriSign, Inc.", "EQUITY", "Information Technology", "US"),
    ("SOUN", "SoundHound AI, Inc.", "EQUITY", "Information Technology", "US"),
    ("IONQ", "IonQ, Inc.", "EQUITY", "Information Technology", "US"),
    ("RGTI", "Rigetti Computing, Inc.", "EQUITY", "Information Technology", "US"),
    ("CRWV", "CoreWeave, Inc.", "EQUITY", "Information Technology", "US"),
    ("ASTS", "AST SpaceMobile, Inc.", "EQUITY", "Communication Services", "US"),
    ("RDDT", "Reddit, Inc.", "EQUITY", "Communication Services", "US"),
    # ---- Communication Services
    ("GOOGL", "Alphabet Inc.", "EQUITY", "Communication Services", "US"),
    ("GOOG", "Alphabet Inc. (Class C)", "EQUITY", "Communication Services", "US"),
    ("META", "Meta Platforms, Inc.", "EQUITY", "Communication Services", "US"),
    ("NFLX", "Netflix, Inc.", "EQUITY", "Communication Services", "US"),
    ("DIS", "The Walt Disney Company", "EQUITY", "Communication Services", "US"),
    ("VZ", "Verizon Communications Inc.", "EQUITY", "Communication Services", "US"),
    ("T", "AT&T Inc.", "EQUITY", "Communication Services", "US"),
    ("TMUS", "T-Mobile US, Inc.", "EQUITY", "Communication Services", "US"),
    ("CMCSA", "Comcast Corporation", "EQUITY", "Communication Services", "US"),
    ("SPOT", "Spotify Technology S.A.", "EQUITY", "Communication Services", "LU"),
    ("WBD", "Warner Bros. Discovery, Inc.", "EQUITY", "Communication Services", "US"),
    ("CHTR", "Charter Communications, Inc.", "EQUITY", "Communication Services", "US"),
    ("EA", "Electronic Arts Inc.", "EQUITY", "Communication Services", "US"),
    ("TTWO", "Take-Two Interactive Software, Inc.", "EQUITY", "Communication Services", "US"),
    ("RBLX", "Roblox Corporation", "EQUITY", "Communication Services", "US"),
    ("SNAP", "Snap Inc.", "EQUITY", "Communication Services", "US"),
    ("PINS", "Pinterest, Inc.", "EQUITY", "Communication Services", "US"),
    ("MTCH", "Match Group, Inc.", "EQUITY", "Communication Services", "US"),
    ("OMC", "Omnicom Group Inc.", "EQUITY", "Communication Services", "US"),
    ("IPG", "The Interpublic Group of Companies, Inc.", "EQUITY", "Communication Services", "US"),
    ("FOXA", "Fox Corporation", "EQUITY", "Communication Services", "US"),
    ("NWSA", "News Corporation", "EQUITY", "Communication Services", "US"),
    ("LYV", "Live Nation Entertainment, Inc.", "EQUITY", "Communication Services", "US"),
    ("TKO", "TKO Group Holdings, Inc.", "EQUITY", "Communication Services", "US"),
    ("LUMN", "Lumen Technologies, Inc.", "EQUITY", "Communication Services", "US"),
    ("ROKU", "Roku, Inc.", "EQUITY", "Communication Services", "US"),
    ("DUOL", "Duolingo, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    # ---- Consumer Discretionary
    ("AMZN", "Amazon.com, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("TSLA", "Tesla, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("HD", "The Home Depot, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("MCD", "McDonald's Corporation", "EQUITY", "Consumer Discretionary", "US"),
    ("NKE", "NIKE, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("F", "Ford Motor Company", "EQUITY", "Consumer Discretionary", "US"),
    ("RIVN", "Rivian Automotive, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("SBUX", "Starbucks Corporation", "EQUITY", "Consumer Discretionary", "US"),
    ("LOW", "Lowe's Companies, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("TJX", "The TJX Companies, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("BKNG", "Booking Holdings Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("ABNB", "Airbnb, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("GM", "General Motors Company", "EQUITY", "Consumer Discretionary", "US"),
    ("LULU", "Lululemon Athletica Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("CMG", "Chipotle Mexican Grill, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("MAR", "Marriott International, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("RCL", "Royal Caribbean Cruises Ltd.", "EQUITY", "Consumer Discretionary", "US"),
    ("CCL", "Carnival Corporation", "EQUITY", "Consumer Discretionary", "US"),
    ("ORLY", "O'Reilly Automotive, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("AZO", "AutoZone, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("ROST", "Ross Stores, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("YUM", "Yum! Brands, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("DHI", "D.R. Horton, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("LEN", "Lennar Corporation", "EQUITY", "Consumer Discretionary", "US"),
    ("NVR", "NVR, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("PHM", "PulteGroup, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("TSCO", "Tractor Supply Company", "EQUITY", "Consumer Discretionary", "US"),
    ("EBAY", "eBay Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("GPC", "Genuine Parts Company", "EQUITY", "Consumer Discretionary", "US"),
    ("BBY", "Best Buy Co., Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("DPZ", "Domino's Pizza, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("HLT", "Hilton Worldwide Holdings Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("EXPE", "Expedia Group, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("LVS", "Las Vegas Sands Corp.", "EQUITY", "Consumer Discretionary", "US"),
    ("MGM", "MGM Resorts International", "EQUITY", "Consumer Discretionary", "US"),
    ("WYNN", "Wynn Resorts, Limited", "EQUITY", "Consumer Discretionary", "US"),
    ("DASH", "DoorDash, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("ETSY", "Etsy, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("DECK", "Deckers Outdoor Corporation", "EQUITY", "Consumer Discretionary", "US"),
    ("TPR", "Tapestry, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("RL", "Ralph Lauren Corporation", "EQUITY", "Consumer Discretionary", "US"),
    ("POOL", "Pool Corporation", "EQUITY", "Consumer Discretionary", "US"),
    ("ULTA", "Ulta Beauty, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("KMX", "CarMax, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("CVNA", "Carvana Co.", "EQUITY", "Consumer Discretionary", "US"),
    ("LCID", "Lucid Group, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("BURL", "Burlington Stores, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("W", "Wayfair Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("CHWY", "Chewy, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("GRAB", "Grab Holdings Limited", "EQUITY", "Industrials", "SG"),
    ("CPNG", "Coupang, Inc.", "EQUITY", "Consumer Discretionary", "KR"),
    ("MELI", "MercadoLibre, Inc.", "EQUITY", "Consumer Discretionary", "UY"),
    ("PTON", "Peloton Interactive, Inc.", "EQUITY", "Consumer Discretionary", "US"),
    ("GME", "GameStop Corp.", "EQUITY", "Consumer Discretionary", "US"),
    ("AMC", "AMC Entertainment Holdings, Inc.", "EQUITY", "Communication Services", "US"),
    # ---- Consumer Staples
    ("PG", "The Procter & Gamble Company", "EQUITY", "Consumer Staples", "US"),
    ("KO", "The Coca-Cola Company", "EQUITY", "Consumer Staples", "US"),
    ("PEP", "PepsiCo, Inc.", "EQUITY", "Consumer Staples", "US"),
    ("WMT", "Walmart Inc.", "EQUITY", "Consumer Staples", "US"),
    ("COST", "Costco Wholesale Corporation", "EQUITY", "Consumer Staples", "US"),
    ("BYND", "Beyond Meat, Inc.", "EQUITY", "Consumer Staples", "US"),
    ("PM", "Philip Morris International Inc.", "EQUITY", "Consumer Staples", "US"),
    ("MO", "Altria Group, Inc.", "EQUITY", "Consumer Staples", "US"),
    ("MDLZ", "Mondelez International, Inc.", "EQUITY", "Consumer Staples", "US"),
    ("CL", "Colgate-Palmolive Company", "EQUITY", "Consumer Staples", "US"),
    ("KHC", "The Kraft Heinz Company", "EQUITY", "Consumer Staples", "US"),
    ("TGT", "Target Corporation", "EQUITY", "Consumer Staples", "US"),
    ("KR", "The Kroger Co.", "EQUITY", "Consumer Staples", "US"),
    ("ADM", "Archer-Daniels-Midland Company", "EQUITY", "Consumer Staples", "US"),
    ("BG", "Bunge Global SA", "EQUITY", "Consumer Staples", "CH"),
    ("GIS", "General Mills, Inc.", "EQUITY", "Consumer Staples", "US"),
    ("K", "Kellanova", "EQUITY", "Consumer Staples", "US"),
    ("HSY", "The Hershey Company", "EQUITY", "Consumer Staples", "US"),
    ("STZ", "Constellation Brands, Inc.", "EQUITY", "Consumer Staples", "US"),
    ("TAP", "Molson Coors Beverage Company", "EQUITY", "Consumer Staples", "US"),
    ("KDP", "Keurig Dr Pepper Inc.", "EQUITY", "Consumer Staples", "US"),
    ("MNST", "Monster Beverage Corporation", "EQUITY", "Consumer Staples", "US"),
    ("KMB", "Kimberly-Clark Corporation", "EQUITY", "Consumer Staples", "US"),
    ("CHD", "Church & Dwight Co., Inc.", "EQUITY", "Consumer Staples", "US"),
    ("CLX", "The Clorox Company", "EQUITY", "Consumer Staples", "US"),
    ("SYY", "Sysco Corporation", "EQUITY", "Consumer Staples", "US"),
    ("HRL", "Hormel Foods Corporation", "EQUITY", "Consumer Staples", "US"),
    ("CAG", "Conagra Brands, Inc.", "EQUITY", "Consumer Staples", "US"),
    ("CPB", "The Campbell's Company", "EQUITY", "Consumer Staples", "US"),
    ("SJM", "The J. M. Smucker Company", "EQUITY", "Consumer Staples", "US"),
    ("TSN", "Tyson Foods, Inc.", "EQUITY", "Consumer Staples", "US"),
    ("EL", "The Estée Lauder Companies Inc.", "EQUITY", "Consumer Staples", "US"),
    ("KVUE", "Kenvue Inc.", "EQUITY", "Consumer Staples", "US"),
    ("CELH", "Celsius Holdings, Inc.", "EQUITY", "Consumer Staples", "US"),
    ("DG", "Dollar General Corporation", "EQUITY", "Consumer Staples", "US"),
    ("DLTR", "Dollar Tree, Inc.", "EQUITY", "Consumer Staples", "US"),
    ("BJ", "BJ's Wholesale Club Holdings, Inc.", "EQUITY", "Consumer Staples", "US"),
    ("CASY", "Casey's General Stores, Inc.", "EQUITY", "Consumer Staples", "US"),
    # ---- Health Care
    ("LLY", "Eli Lilly and Company", "EQUITY", "Health Care", "US"),
    ("UNH", "UnitedHealth Group Incorporated", "EQUITY", "Health Care", "US"),
    ("JNJ", "Johnson & Johnson", "EQUITY", "Health Care", "US"),
    ("PFE", "Pfizer Inc.", "EQUITY", "Health Care", "US"),
    ("MRK", "Merck & Co., Inc.", "EQUITY", "Health Care", "US"),
    ("ABBV", "AbbVie Inc.", "EQUITY", "Health Care", "US"),
    ("TMO", "Thermo Fisher Scientific Inc.", "EQUITY", "Health Care", "US"),
    ("ABT", "Abbott Laboratories", "EQUITY", "Health Care", "US"),
    ("AMGN", "Amgen Inc.", "EQUITY", "Health Care", "US"),
    ("GILD", "Gilead Sciences, Inc.", "EQUITY", "Health Care", "US"),
    ("ISRG", "Intuitive Surgical, Inc.", "EQUITY", "Health Care", "US"),
    ("CVS", "CVS Health Corporation", "EQUITY", "Health Care", "US"),
    ("MRNA", "Moderna, Inc.", "EQUITY", "Health Care", "US"),
    ("REGN", "Regeneron Pharmaceuticals, Inc.", "EQUITY", "Health Care", "US"),
    ("VRTX", "Vertex Pharmaceuticals Incorporated", "EQUITY", "Health Care", "US"),
    ("DHR", "Danaher Corporation", "EQUITY", "Health Care", "US"),
    ("BMY", "Bristol-Myers Squibb Company", "EQUITY", "Health Care", "US"),
    ("MDT", "Medtronic plc", "EQUITY", "Health Care", "IE"),
    ("SYK", "Stryker Corporation", "EQUITY", "Health Care", "US"),
    ("BSX", "Boston Scientific Corporation", "EQUITY", "Health Care", "US"),
    ("ELV", "Elevance Health, Inc.", "EQUITY", "Health Care", "US"),
    ("CI", "The Cigna Group", "EQUITY", "Health Care", "US"),
    ("HUM", "Humana Inc.", "EQUITY", "Health Care", "US"),
    ("CNC", "Centene Corporation", "EQUITY", "Health Care", "US"),
    ("MCK", "McKesson Corporation", "EQUITY", "Health Care", "US"),
    ("COR", "Cencora, Inc.", "EQUITY", "Health Care", "US"),
    ("CAH", "Cardinal Health, Inc.", "EQUITY", "Health Care", "US"),
    ("ZTS", "Zoetis Inc.", "EQUITY", "Health Care", "US"),
    ("BDX", "Becton, Dickinson and Company", "EQUITY", "Health Care", "US"),
    ("EW", "Edwards Lifesciences Corporation", "EQUITY", "Health Care", "US"),
    ("IDXX", "IDEXX Laboratories, Inc.", "EQUITY", "Health Care", "US"),
    ("A", "Agilent Technologies, Inc.", "EQUITY", "Health Care", "US"),
    ("IQV", "IQVIA Holdings Inc.", "EQUITY", "Health Care", "US"),
    ("MTD", "Mettler-Toledo International Inc.", "EQUITY", "Health Care", "US"),
    ("RMD", "ResMed Inc.", "EQUITY", "Health Care", "US"),
    ("DXCM", "DexCom, Inc.", "EQUITY", "Health Care", "US"),
    ("ALGN", "Align Technology, Inc.", "EQUITY", "Health Care", "US"),
    ("BIIB", "Biogen Inc.", "EQUITY", "Health Care", "US"),
    ("ILMN", "Illumina, Inc.", "EQUITY", "Health Care", "US"),
    ("HOLX", "Hologic, Inc.", "EQUITY", "Health Care", "US"),
    ("BAX", "Baxter International Inc.", "EQUITY", "Health Care", "US"),
    ("ZBH", "Zimmer Biomet Holdings, Inc.", "EQUITY", "Health Care", "US"),
    ("STE", "STERIS plc", "EQUITY", "Health Care", "IE"),
    ("WST", "West Pharmaceutical Services, Inc.", "EQUITY", "Health Care", "US"),
    ("INCY", "Incyte Corporation", "EQUITY", "Health Care", "US"),
    ("HIMS", "Hims & Hers Health, Inc.", "EQUITY", "Health Care", "US"),
    ("ALNY", "Alnylam Pharmaceuticals, Inc.", "EQUITY", "Health Care", "US"),
    ("NBIX", "Neurocrine Biosciences, Inc.", "EQUITY", "Health Care", "US"),
    ("VEEV", "Veeva Systems Inc.", "EQUITY", "Health Care", "US"),
    ("DVA", "DaVita Inc.", "EQUITY", "Health Care", "US"),
    ("UHS", "Universal Health Services, Inc.", "EQUITY", "Health Care", "US"),
    ("HCA", "HCA Healthcare, Inc.", "EQUITY", "Health Care", "US"),
    ("LH", "Labcorp Holdings Inc.", "EQUITY", "Health Care", "US"),
    ("DGX", "Quest Diagnostics Incorporated", "EQUITY", "Health Care", "US"),
    ("MOH", "Molina Healthcare, Inc.", "EQUITY", "Health Care", "US"),
    ("PODD", "Insulet Corporation", "EQUITY", "Health Care", "US"),
    ("TECH", "Bio-Techne Corporation", "EQUITY", "Health Care", "US"),
    ("VTRS", "Viatris Inc.", "EQUITY", "Health Care", "US"),
    ("ARGX", "argenx SE (ADR)", "ADR", "Health Care", "NL"),
    ("CRSP", "CRISPR Therapeutics AG", "EQUITY", "Health Care", "CH"),
    # ---- Financials
    ("JPM", "JPMorgan Chase & Co.", "EQUITY", "Financials", "US"),
    ("GS", "The Goldman Sachs Group, Inc.", "EQUITY", "Financials", "US"),
    ("BAC", "Bank of America Corporation", "EQUITY", "Financials", "US"),
    ("MS", "Morgan Stanley", "EQUITY", "Financials", "US"),
    ("BRK-B", "Berkshire Hathaway Inc. (Class B)", "EQUITY", "Financials", "US"),
    ("V", "Visa Inc.", "EQUITY", "Financials", "US"),
    ("BLK", "BlackRock, Inc.", "EQUITY", "Financials", "US"),
    ("WFC", "Wells Fargo & Company", "EQUITY", "Financials", "US"),
    ("C", "Citigroup Inc.", "EQUITY", "Financials", "US"),
    ("AXP", "American Express Company", "EQUITY", "Financials", "US"),
    ("SCHW", "The Charles Schwab Corporation", "EQUITY", "Financials", "US"),
    ("MA", "Mastercard Incorporated", "EQUITY", "Financials", "US"),
    ("PYPL", "PayPal Holdings, Inc.", "EQUITY", "Financials", "US"),
    ("COF", "Capital One Financial Corporation", "EQUITY", "Financials", "US"),
    ("USB", "U.S. Bancorp", "EQUITY", "Financials", "US"),
    ("PGR", "The Progressive Corporation", "EQUITY", "Financials", "US"),
    ("CB", "Chubb Limited", "EQUITY", "Financials", "CH"),
    ("MET", "MetLife, Inc.", "EQUITY", "Financials", "US"),
    ("KKR", "KKR & Co. Inc.", "EQUITY", "Financials", "US"),
    ("BX", "Blackstone Inc.", "EQUITY", "Financials", "US"),
    ("PNC", "The PNC Financial Services Group, Inc.", "EQUITY", "Financials", "US"),
    ("TFC", "Truist Financial Corporation", "EQUITY", "Financials", "US"),
    ("BK", "The Bank of New York Mellon Corporation", "EQUITY", "Financials", "US"),
    ("STT", "State Street Corporation", "EQUITY", "Financials", "US"),
    ("NTRS", "Northern Trust Corporation", "EQUITY", "Financials", "US"),
    ("AIG", "American International Group, Inc.", "EQUITY", "Financials", "US"),
    ("TRV", "The Travelers Companies, Inc.", "EQUITY", "Financials", "US"),
    ("ALL", "The Allstate Corporation", "EQUITY", "Financials", "US"),
    ("HIG", "The Hartford Insurance Group, Inc.", "EQUITY", "Financials", "US"),
    ("AFL", "Aflac Incorporated", "EQUITY", "Financials", "US"),
    ("PRU", "Prudential Financial, Inc.", "EQUITY", "Financials", "US"),
    ("MMC", "Marsh & McLennan Companies, Inc.", "EQUITY", "Financials", "US"),
    ("AON", "Aon plc", "EQUITY", "Financials", "IE"),
    ("AJG", "Arthur J. Gallagher & Co.", "EQUITY", "Financials", "US"),
    ("WTW", "Willis Towers Watson Public Limited Company", "EQUITY", "Financials", "IE"),
    ("BRO", "Brown & Brown, Inc.", "EQUITY", "Financials", "US"),
    ("ICE", "Intercontinental Exchange, Inc.", "EQUITY", "Financials", "US"),
    ("CME", "CME Group Inc.", "EQUITY", "Financials", "US"),
    ("SPGI", "S&P Global Inc.", "EQUITY", "Financials", "US"),
    ("MCO", "Moody's Corporation", "EQUITY", "Financials", "US"),
    ("MSCI", "MSCI Inc.", "EQUITY", "Financials", "US"),
    ("NDAQ", "Nasdaq, Inc.", "EQUITY", "Financials", "US"),
    ("CBOE", "Cboe Global Markets, Inc.", "EQUITY", "Financials", "US"),
    ("COIN", "Coinbase Global, Inc.", "EQUITY", "Financials", "US"),
    ("HOOD", "Robinhood Markets, Inc.", "EQUITY", "Financials", "US"),
    ("SOFI", "SoFi Technologies, Inc.", "EQUITY", "Financials", "US"),
    ("APO", "Apollo Global Management, Inc.", "EQUITY", "Financials", "US"),
    ("ARES", "Ares Management Corporation", "EQUITY", "Financials", "US"),
    ("OWL", "Blue Owl Capital Inc.", "EQUITY", "Financials", "US"),
    ("CG", "The Carlyle Group Inc.", "EQUITY", "Financials", "US"),
    ("SYF", "Synchrony Financial", "EQUITY", "Financials", "US"),
    ("ALLY", "Ally Financial Inc.", "EQUITY", "Financials", "US"),
    ("FITB", "Fifth Third Bancorp", "EQUITY", "Financials", "US"),
    ("MTB", "M&T Bank Corporation", "EQUITY", "Financials", "US"),
    ("RF", "Regions Financial Corporation", "EQUITY", "Financials", "US"),
    ("HBAN", "Huntington Bancshares Incorporated", "EQUITY", "Financials", "US"),
    ("KEY", "KeyCorp", "EQUITY", "Financials", "US"),
    ("CFG", "Citizens Financial Group, Inc.", "EQUITY", "Financials", "US"),
    ("FIS", "Fidelity National Information Services, Inc.", "EQUITY", "Financials", "US"),
    ("FI", "Fiserv, Inc.", "EQUITY", "Financials", "US"),
    ("GPN", "Global Payments Inc.", "EQUITY", "Financials", "US"),
    ("TW", "Tradeweb Markets Inc.", "EQUITY", "Financials", "US"),
    ("MKTX", "MarketAxess Holdings Inc.", "EQUITY", "Financials", "US"),
    ("LPLA", "LPL Financial Holdings Inc.", "EQUITY", "Financials", "US"),
    ("RJF", "Raymond James Financial, Inc.", "EQUITY", "Financials", "US"),
    ("AMP", "Ameriprise Financial, Inc.", "EQUITY", "Financials", "US"),
    ("IBKR", "Interactive Brokers Group, Inc.", "EQUITY", "Financials", "US"),
    ("AFRM", "Affirm Holdings, Inc.", "EQUITY", "Financials", "US"),
    ("UPST", "Upstart Holdings, Inc.", "EQUITY", "Financials", "US"),
    ("NU", "Nu Holdings Ltd.", "EQUITY", "Financials", "BR"),
    ("CRBG", "Corebridge Financial, Inc.", "EQUITY", "Financials", "US"),
    ("EQH", "Equitable Holdings, Inc.", "EQUITY", "Financials", "US"),
    ("PFG", "Principal Financial Group, Inc.", "EQUITY", "Financials", "US"),
    ("CINF", "Cincinnati Financial Corporation", "EQUITY", "Financials", "US"),
    ("WRB", "W. R. Berkley Corporation", "EQUITY", "Financials", "US"),
    ("L", "Loews Corporation", "EQUITY", "Financials", "US"),
    ("BEN", "Franklin Resources, Inc.", "EQUITY", "Financials", "US"),
    ("TROW", "T. Rowe Price Group, Inc.", "EQUITY", "Financials", "US"),
    ("IVZ", "Invesco Ltd.", "EQUITY", "Financials", "US"),
    ("CRCL", "Circle Internet Group, Inc.", "EQUITY", "Financials", "US"),
    # ---- Industrials
    ("CAT", "Caterpillar Inc.", "EQUITY", "Industrials", "US"),
    ("GE", "GE Aerospace", "EQUITY", "Industrials", "US"),
    ("UNP", "Union Pacific Corporation", "EQUITY", "Industrials", "US"),
    ("BA", "The Boeing Company", "EQUITY", "Industrials", "US"),
    ("RTX", "RTX Corporation", "EQUITY", "Industrials", "US"),
    ("UPS", "United Parcel Service, Inc.", "EQUITY", "Industrials", "US"),
    ("AAL", "American Airlines Group Inc.", "EQUITY", "Industrials", "US"),
    ("HON", "Honeywell International Inc.", "EQUITY", "Industrials", "US"),
    ("LMT", "Lockheed Martin Corporation", "EQUITY", "Industrials", "US"),
    ("SPCX", "Space Exploration Technologies Corp.", "EQUITY", "Industrials", "US"),
    ("DE", "Deere & Company", "EQUITY", "Industrials", "US"),
    ("GD", "General Dynamics Corporation", "EQUITY", "Industrials", "US"),
    ("NOC", "Northrop Grumman Corporation", "EQUITY", "Industrials", "US"),
    ("FDX", "FedEx Corporation", "EQUITY", "Industrials", "US"),
    ("ETN", "Eaton Corporation plc", "EQUITY", "Industrials", "IE"),
    ("WM", "Waste Management, Inc.", "EQUITY", "Industrials", "US"),
    ("DAL", "Delta Air Lines, Inc.", "EQUITY", "Industrials", "US"),
    ("UBER", "Uber Technologies, Inc.", "EQUITY", "Industrials", "US"),
    ("GEV", "GE Vernova Inc.", "EQUITY", "Industrials", "US"),
    ("ADP", "Automatic Data Processing, Inc.", "EQUITY", "Industrials", "US"),
    ("PAYX", "Paychex, Inc.", "EQUITY", "Industrials", "US"),
    ("CTAS", "Cintas Corporation", "EQUITY", "Industrials", "US"),
    ("CSX", "CSX Corporation", "EQUITY", "Industrials", "US"),
    ("NSC", "Norfolk Southern Corporation", "EQUITY", "Industrials", "US"),
    ("LUV", "Southwest Airlines Co.", "EQUITY", "Industrials", "US"),
    ("UAL", "United Airlines Holdings, Inc.", "EQUITY", "Industrials", "US"),
    ("JBHT", "J.B. Hunt Transport Services, Inc.", "EQUITY", "Industrials", "US"),
    ("ODFL", "Old Dominion Freight Line, Inc.", "EQUITY", "Industrials", "US"),
    ("XPO", "XPO, Inc.", "EQUITY", "Industrials", "US"),
    ("EMR", "Emerson Electric Co.", "EQUITY", "Industrials", "US"),
    ("ITW", "Illinois Tool Works Inc.", "EQUITY", "Industrials", "US"),
    ("PH", "Parker-Hannifin Corporation", "EQUITY", "Industrials", "US"),
    ("ROK", "Rockwell Automation, Inc.", "EQUITY", "Industrials", "US"),
    ("CMI", "Cummins Inc.", "EQUITY", "Industrials", "US"),
    ("PCAR", "PACCAR Inc", "EQUITY", "Industrials", "US"),
    ("MMM", "3M Company", "EQUITY", "Industrials", "US"),
    ("DOV", "Dover Corporation", "EQUITY", "Industrials", "US"),
    ("AME", "AMETEK, Inc.", "EQUITY", "Industrials", "US"),
    ("FAST", "Fastenal Company", "EQUITY", "Industrials", "US"),
    ("GWW", "W.W. Grainger, Inc.", "EQUITY", "Industrials", "US"),
    ("URI", "United Rentals, Inc.", "EQUITY", "Industrials", "US"),
    ("PWR", "Quanta Services, Inc.", "EQUITY", "Industrials", "US"),
    ("JCI", "Johnson Controls International plc", "EQUITY", "Industrials", "IE"),
    ("CARR", "Carrier Global Corporation", "EQUITY", "Industrials", "US"),
    ("OTIS", "Otis Worldwide Corporation", "EQUITY", "Industrials", "US"),
    ("TT", "Trane Technologies plc", "EQUITY", "Industrials", "IE"),
    ("LHX", "L3Harris Technologies, Inc.", "EQUITY", "Industrials", "US"),
    ("HII", "Huntington Ingalls Industries, Inc.", "EQUITY", "Industrials", "US"),
    ("TDG", "TransDigm Group Incorporated", "EQUITY", "Industrials", "US"),
    ("HWM", "Howmet Aerospace Inc.", "EQUITY", "Industrials", "US"),
    ("AXON", "Axon Enterprise, Inc.", "EQUITY", "Industrials", "US"),
    ("RSG", "Republic Services, Inc.", "EQUITY", "Industrials", "US"),
    ("VRSK", "Verisk Analytics, Inc.", "EQUITY", "Industrials", "US"),
    ("EFX", "Equifax Inc.", "EQUITY", "Industrials", "US"),
    ("BR", "Broadridge Financial Solutions, Inc.", "EQUITY", "Industrials", "US"),
    ("CPRT", "Copart, Inc.", "EQUITY", "Industrials", "US"),
    ("LII", "Lennox International Inc.", "EQUITY", "Industrials", "US"),
    ("SWK", "Stanley Black & Decker, Inc.", "EQUITY", "Industrials", "US"),
    ("MAS", "Masco Corporation", "EQUITY", "Industrials", "US"),
    ("IR", "Ingersoll Rand Inc.", "EQUITY", "Industrials", "US"),
    ("XYL", "Xylem Inc.", "EQUITY", "Industrials", "US"),
    ("FTV", "Fortive Corporation", "EQUITY", "Industrials", "US"),
    ("WAB", "Westinghouse Air Brake Technologies Corporation", "EQUITY", "Industrials", "US"),
    ("TXT", "Textron Inc.", "EQUITY", "Industrials", "US"),
    ("LDOS", "Leidos Holdings, Inc.", "EQUITY", "Industrials", "US"),
    ("BAH", "Booz Allen Hamilton Holding Corporation", "EQUITY", "Industrials", "US"),
    ("J", "Jacobs Solutions Inc.", "EQUITY", "Industrials", "US"),
    ("ACM", "AECOM", "EQUITY", "Industrials", "US"),
    ("CHRW", "C.H. Robinson Worldwide, Inc.", "EQUITY", "Industrials", "US"),
    ("EXPD", "Expeditors International of Washington, Inc.", "EQUITY", "Industrials", "US"),
    ("RKLB", "Rocket Lab Corporation", "EQUITY", "Industrials", "US"),
    ("JOBY", "Joby Aviation, Inc.", "EQUITY", "Industrials", "US"),
    ("ACHR", "Archer Aviation Inc.", "EQUITY", "Industrials", "US"),
    ("VRT", "Vertiv Holdings Co", "EQUITY", "Industrials", "US"),
    ("SYM", "Symbotic Inc.", "EQUITY", "Industrials", "US"),
    # ---- Energy
    ("XOM", "Exxon Mobil Corporation", "EQUITY", "Energy", "US"),
    ("CVX", "Chevron Corporation", "EQUITY", "Energy", "US"),
    ("COP", "ConocoPhillips", "EQUITY", "Energy", "US"),
    ("SLB", "Schlumberger Limited", "EQUITY", "Energy", "US"),
    ("OXY", "Occidental Petroleum Corporation", "EQUITY", "Energy", "US"),
    ("EOG", "EOG Resources, Inc.", "EQUITY", "Energy", "US"),
    ("MPC", "Marathon Petroleum Corporation", "EQUITY", "Energy", "US"),
    ("PSX", "Phillips 66", "EQUITY", "Energy", "US"),
    ("KMI", "Kinder Morgan, Inc.", "EQUITY", "Energy", "US"),
    ("DVN", "Devon Energy Corporation", "EQUITY", "Energy", "US"),
    ("HAL", "Halliburton Company", "EQUITY", "Energy", "US"),
    ("BKR", "Baker Hughes Company", "EQUITY", "Energy", "US"),
    ("WMB", "The Williams Companies, Inc.", "EQUITY", "Energy", "US"),
    ("OKE", "ONEOK, Inc.", "EQUITY", "Energy", "US"),
    ("VLO", "Valero Energy Corporation", "EQUITY", "Energy", "US"),
    ("FANG", "Diamondback Energy, Inc.", "EQUITY", "Energy", "US"),
    ("CTRA", "Coterra Energy Inc.", "EQUITY", "Energy", "US"),
    ("APA", "APA Corporation", "EQUITY", "Energy", "US"),
    ("EQT", "EQT Corporation", "EQUITY", "Energy", "US"),
    ("TRGP", "Targa Resources Corp.", "EQUITY", "Energy", "US"),
    ("LNG", "Cheniere Energy, Inc.", "EQUITY", "Energy", "US"),
    ("EXE", "Expand Energy Corporation", "EQUITY", "Energy", "US"),
    ("DINO", "HF Sinclair Corporation", "EQUITY", "Energy", "US"),
    ("PBF", "PBF Energy Inc.", "EQUITY", "Energy", "US"),
    ("FTI", "TechnipFMC plc", "EQUITY", "Energy", "GB"),
    ("NOV", "NOV Inc.", "EQUITY", "Energy", "US"),
    ("OVV", "Ovintiv Inc.", "EQUITY", "Energy", "US"),
    ("AR", "Antero Resources Corporation", "EQUITY", "Energy", "US"),
    # ---- Materials
    ("LIN", "Linde plc", "EQUITY", "Materials", "IE"),
    ("FCX", "Freeport-McMoRan Inc.", "EQUITY", "Materials", "US"),
    ("NEM", "Newmont Corporation", "EQUITY", "Materials", "US"),
    ("NUE", "Nucor Corporation", "EQUITY", "Materials", "US"),
    ("DOW", "Dow Inc.", "EQUITY", "Materials", "US"),
    ("SHW", "The Sherwin-Williams Company", "EQUITY", "Materials", "US"),
    ("APD", "Air Products and Chemicals, Inc.", "EQUITY", "Materials", "US"),
    ("ECL", "Ecolab Inc.", "EQUITY", "Materials", "US"),
    ("DD", "DuPont de Nemours, Inc.", "EQUITY", "Materials", "US"),
    ("PPG", "PPG Industries, Inc.", "EQUITY", "Materials", "US"),
    ("CTVA", "Corteva, Inc.", "EQUITY", "Materials", "US"),
    ("VMC", "Vulcan Materials Company", "EQUITY", "Materials", "US"),
    ("MLM", "Martin Marietta Materials, Inc.", "EQUITY", "Materials", "US"),
    ("ALB", "Albemarle Corporation", "EQUITY", "Materials", "US"),
    ("CF", "CF Industries Holdings, Inc.", "EQUITY", "Materials", "US"),
    ("MOS", "The Mosaic Company", "EQUITY", "Materials", "US"),
    ("IFF", "International Flavors & Fragrances Inc.", "EQUITY", "Materials", "US"),
    ("LYB", "LyondellBasell Industries N.V.", "EQUITY", "Materials", "NL"),
    ("STLD", "Steel Dynamics, Inc.", "EQUITY", "Materials", "US"),
    ("CLF", "Cleveland-Cliffs Inc.", "EQUITY", "Materials", "US"),
    ("AA", "Alcoa Corporation", "EQUITY", "Materials", "US"),
    ("IP", "International Paper Company", "EQUITY", "Materials", "US"),
    ("PKG", "Packaging Corporation of America", "EQUITY", "Materials", "US"),
    ("BALL", "Ball Corporation", "EQUITY", "Materials", "US"),
    ("AMCR", "Amcor plc", "EQUITY", "Materials", "CH"),
    ("AVY", "Avery Dennison Corporation", "EQUITY", "Materials", "US"),
    ("EMN", "Eastman Chemical Company", "EQUITY", "Materials", "US"),
    ("MP", "MP Materials Corp.", "EQUITY", "Materials", "US"),
    ("CCJ", "Cameco Corporation", "EQUITY", "Energy", "CA"),
    # ---- Utilities
    ("NEE", "NextEra Energy, Inc.", "EQUITY", "Utilities", "US"),
    ("DUK", "Duke Energy Corporation", "EQUITY", "Utilities", "US"),
    ("SO", "The Southern Company", "EQUITY", "Utilities", "US"),
    ("D", "Dominion Energy, Inc.", "EQUITY", "Utilities", "US"),
    ("AEP", "American Electric Power Company, Inc.", "EQUITY", "Utilities", "US"),
    ("EXC", "Exelon Corporation", "EQUITY", "Utilities", "US"),
    ("SRE", "Sempra", "EQUITY", "Utilities", "US"),
    ("XEL", "Xcel Energy Inc.", "EQUITY", "Utilities", "US"),
    ("PEG", "Public Service Enterprise Group Incorporated", "EQUITY", "Utilities", "US"),
    ("ED", "Consolidated Edison, Inc.", "EQUITY", "Utilities", "US"),
    ("EIX", "Edison International", "EQUITY", "Utilities", "US"),
    ("WEC", "WEC Energy Group, Inc.", "EQUITY", "Utilities", "US"),
    ("ES", "Eversource Energy", "EQUITY", "Utilities", "US"),
    ("DTE", "DTE Energy Company", "EQUITY", "Utilities", "US"),
    ("PCG", "PG&E Corporation", "EQUITY", "Utilities", "US"),
    ("ETR", "Entergy Corporation", "EQUITY", "Utilities", "US"),
    ("AEE", "Ameren Corporation", "EQUITY", "Utilities", "US"),
    ("CMS", "CMS Energy Corporation", "EQUITY", "Utilities", "US"),
    ("CNP", "CenterPoint Energy, Inc.", "EQUITY", "Utilities", "US"),
    ("FE", "FirstEnergy Corp.", "EQUITY", "Utilities", "US"),
    ("PPL", "PPL Corporation", "EQUITY", "Utilities", "US"),
    ("NRG", "NRG Energy, Inc.", "EQUITY", "Utilities", "US"),
    ("VST", "Vistra Corp.", "EQUITY", "Utilities", "US"),
    ("CEG", "Constellation Energy Corporation", "EQUITY", "Utilities", "US"),
    ("AWK", "American Water Works Company, Inc.", "EQUITY", "Utilities", "US"),
    ("ATO", "Atmos Energy Corporation", "EQUITY", "Utilities", "US"),
    ("NI", "NiSource Inc.", "EQUITY", "Utilities", "US"),
    ("EVRG", "Evergy, Inc.", "EQUITY", "Utilities", "US"),
    ("LNT", "Alliant Energy Corporation", "EQUITY", "Utilities", "US"),
    ("OKLO", "Oklo Inc.", "EQUITY", "Utilities", "US"),
    # ---- Real Estate
    ("PLD", "Prologis, Inc.", "REIT", "Real Estate", "US"),
    ("AMT", "American Tower Corporation", "REIT", "Real Estate", "US"),
    ("O", "Realty Income Corporation", "REIT", "Real Estate", "US"),
    ("SPG", "Simon Property Group, Inc.", "REIT", "Real Estate", "US"),
    ("EQIX", "Equinix, Inc.", "REIT", "Real Estate", "US"),
    ("PSA", "Public Storage", "REIT", "Real Estate", "US"),
    ("CCI", "Crown Castle Inc.", "REIT", "Real Estate", "US"),
    ("DLR", "Digital Realty Trust, Inc.", "REIT", "Real Estate", "US"),
    ("WELL", "Welltower Inc.", "REIT", "Real Estate", "US"),
    ("VTR", "Ventas, Inc.", "REIT", "Real Estate", "US"),
    ("AVB", "AvalonBay Communities, Inc.", "REIT", "Real Estate", "US"),
    ("EQR", "Equity Residential", "REIT", "Real Estate", "US"),
    ("ESS", "Essex Property Trust, Inc.", "REIT", "Real Estate", "US"),
    ("INVH", "Invitation Homes Inc.", "REIT", "Real Estate", "US"),
    ("MAA", "Mid-America Apartment Communities, Inc.", "REIT", "Real Estate", "US"),
    ("ARE", "Alexandria Real Estate Equities, Inc.", "REIT", "Real Estate", "US"),
    ("BXP", "BXP, Inc.", "REIT", "Real Estate", "US"),
    ("VICI", "VICI Properties Inc.", "REIT", "Real Estate", "US"),
    ("IRM", "Iron Mountain Incorporated", "REIT", "Real Estate", "US"),
    ("SBAC", "SBA Communications Corporation", "REIT", "Real Estate", "US"),
    ("EXR", "Extra Space Storage Inc.", "REIT", "Real Estate", "US"),
    ("WY", "Weyerhaeuser Company", "REIT", "Real Estate", "US"),
    ("KIM", "Kimco Realty Corporation", "REIT", "Real Estate", "US"),
    ("REG", "Regency Centers Corporation", "REIT", "Real Estate", "US"),
    ("HST", "Host Hotels & Resorts, Inc.", "REIT", "Real Estate", "US"),
    ("CBRE", "CBRE Group, Inc.", "EQUITY", "Real Estate", "US"),
    ("CSGP", "CoStar Group, Inc.", "EQUITY", "Real Estate", "US"),
    ("Z", "Zillow Group, Inc.", "EQUITY", "Real Estate", "US"),
    # ---- ADRs and foreign listings
    ("TSM", "Taiwan Semiconductor Manufacturing (ADR)", "ADR", "Information Technology", "TW"),
    ("TM", "Toyota Motor Corporation (ADR)", "ADR", "Consumer Discretionary", "JP"),
    ("ASML", "ASML Holding N.V. (ADR)", "ADR", "Information Technology", "NL"),
    ("NVO", "Novo Nordisk A/S (ADR)", "ADR", "Health Care", "DK"),
    ("BABA", "Alibaba Group Holding Limited (ADR)", "ADR", "Consumer Discretionary", "CN"),
    ("SAP", "SAP SE (ADR)", "ADR", "Information Technology", "DE"),
    ("SHEL", "Shell plc (ADR)", "ADR", "Energy", "GB"),
    ("BP", "BP p.l.c. (ADR)", "ADR", "Energy", "GB"),
    ("TTE", "TotalEnergies SE (ADR)", "ADR", "Energy", "FR"),
    ("UL", "Unilever PLC (ADR)", "ADR", "Consumer Staples", "GB"),
    ("BHP", "BHP Group Limited (ADR)", "ADR", "Materials", "AU"),
    ("RIO", "Rio Tinto Group (ADR)", "ADR", "Materials", "GB"),
    ("VALE", "Vale S.A. (ADR)", "ADR", "Materials", "BR"),
    ("PBR", "Petróleo Brasileiro S.A. - Petrobras (ADR)", "ADR", "Energy", "BR"),
    ("NVS", "Novartis AG (ADR)", "ADR", "Health Care", "CH"),
    ("AZN", "AstraZeneca PLC (ADR)", "ADR", "Health Care", "GB"),
    ("GSK", "GSK plc (ADR)", "ADR", "Health Care", "GB"),
    ("SNY", "Sanofi (ADR)", "ADR", "Health Care", "FR"),
    ("HSBC", "HSBC Holdings plc (ADR)", "ADR", "Financials", "GB"),
    ("MUFG", "Mitsubishi UFJ Financial Group, Inc. (ADR)", "ADR", "Financials", "JP"),
    ("SMFG", "Sumitomo Mitsui Financial Group, Inc. (ADR)", "ADR", "Financials", "JP"),
    ("SONY", "Sony Group Corporation (ADR)", "ADR", "Consumer Discretionary", "JP"),
    ("PDD", "PDD Holdings Inc. (ADR)", "ADR", "Consumer Discretionary", "CN"),
    ("JD", "JD.com, Inc. (ADR)", "ADR", "Consumer Discretionary", "CN"),
    ("BIDU", "Baidu, Inc. (ADR)", "ADR", "Communication Services", "CN"),
    ("NTES", "NetEase, Inc. (ADR)", "ADR", "Communication Services", "CN"),
    ("TCOM", "Trip.com Group Limited (ADR)", "ADR", "Consumer Discretionary", "CN"),
    ("NIO", "NIO Inc. (ADR)", "ADR", "Consumer Discretionary", "CN"),
    ("XPEV", "XPeng Inc. (ADR)", "ADR", "Consumer Discretionary", "CN"),
    ("LI", "Li Auto Inc. (ADR)", "ADR", "Consumer Discretionary", "CN"),
    ("BNTX", "BioNTech SE (ADR)", "ADR", "Health Care", "DE"),
    ("SE", "Sea Limited (ADR)", "ADR", "Communication Services", "SG"),
    ("ARM", "Arm Holdings plc (ADR)", "ADR", "Information Technology", "GB"),
    ("INFY", "Infosys Limited (ADR)", "ADR", "Information Technology", "IN"),
    ("WIT", "Wipro Limited (ADR)", "ADR", "Information Technology", "IN"),
    ("HDB", "HDFC Bank Limited (ADR)", "ADR", "Financials", "IN"),
    ("IBN", "ICICI Bank Limited (ADR)", "ADR", "Financials", "IN"),
    ("TEVA", "Teva Pharmaceutical Industries Limited (ADR)", "ADR", "Health Care", "IL"),
    ("DEO", "Diageo plc (ADR)", "ADR", "Consumer Staples", "GB"),
    ("BUD", "Anheuser-Busch InBev SA/NV (ADR)", "ADR", "Consumer Staples", "BE"),
    ("RELX", "RELX PLC (ADR)", "ADR", "Industrials", "GB"),
    ("SAN", "Banco Santander, S.A. (ADR)", "ADR", "Financials", "ES"),
    ("BBVA", "Banco Bilbao Vizcaya Argentaria, S.A. (ADR)", "ADR", "Financials", "ES"),
    ("ING", "ING Groep N.V. (ADR)", "ADR", "Financials", "NL"),
    ("UBS", "UBS Group AG", "ADR", "Financials", "CH"),
    ("DB", "Deutsche Bank Aktiengesellschaft", "ADR", "Financials", "DE"),
    ("BCS", "Barclays PLC (ADR)", "ADR", "Financials", "GB"),
    ("LYG", "Lloyds Banking Group plc (ADR)", "ADR", "Financials", "GB"),
    ("NWG", "NatWest Group plc (ADR)", "ADR", "Financials", "GB"),
    ("ERIC", "Telefonaktiebolaget LM Ericsson (ADR)", "ADR", "Information Technology", "SE"),
    ("NOK", "Nokia Oyj (ADR)", "ADR", "Information Technology", "FI"),
    ("STM", "STMicroelectronics N.V. (ADR)", "ADR", "Information Technology", "CH"),
    ("UMC", "United Microelectronics Corporation (ADR)", "ADR", "Information Technology", "TW"),
    ("CHT", "Chunghwa Telecom Co., Ltd. (ADR)", "ADR", "Communication Services", "TW"),
    ("KB", "KB Financial Group Inc. (ADR)", "ADR", "Financials", "KR"),
    ("SHG", "Shinhan Financial Group Co., Ltd. (ADR)", "ADR", "Financials", "KR"),
    ("YUMC", "Yum China Holdings, Inc.", "EQUITY", "Consumer Discretionary", "CN"),
    ("MT", "ArcelorMittal S.A. (ADR)", "ADR", "Materials", "LU"),
    ("E", "Eni S.p.A. (ADR)", "ADR", "Energy", "IT"),
    ("EQNR", "Equinor ASA (ADR)", "ADR", "Energy", "NO"),
    ("CNQ", "Canadian Natural Resources Limited", "ADR", "Energy", "CA"),
    ("SU", "Suncor Energy Inc.", "ADR", "Energy", "CA"),
    ("ENB", "Enbridge Inc.", "ADR", "Energy", "CA"),
    ("CP", "Canadian Pacific Kansas City Limited", "ADR", "Industrials", "CA"),
    ("CNI", "Canadian National Railway Company", "ADR", "Industrials", "CA"),
    ("RY", "Royal Bank of Canada", "ADR", "Financials", "CA"),
    ("TD", "The Toronto-Dominion Bank", "ADR", "Financials", "CA"),
    ("BNS", "The Bank of Nova Scotia", "ADR", "Financials", "CA"),
    ("BMO", "Bank of Montreal", "ADR", "Financials", "CA"),
    ("BAM", "Brookfield Asset Management Ltd.", "ADR", "Financials", "CA"),
    ("BN", "Brookfield Corporation", "ADR", "Financials", "CA"),
    ("ABEV", "Ambev S.A. (ADR)", "ADR", "Consumer Staples", "BR"),
    ("ITUB", "Itaú Unibanco Holding S.A. (ADR)", "ADR", "Financials", "BR"),
    ("BBD", "Banco Bradesco S.A. (ADR)", "ADR", "Financials", "BR"),
    ("AMX", "América Movil, S.A.B. de C.V. (ADR)", "ADR", "Communication Services", "MX"),
    ("FMX", "Fomento Económico Mexicano, S.A.B. de C.V. (ADR)", "ADR", "Consumer Staples", "MX"),
    ("TLK", "Telkom Indonesia (ADR)", "ADR", "Communication Services", "ID"),
    ("VOD", "Vodafone Group Public Limited Company (ADR)", "ADR", "Communication Services", "GB"),
    ("PHG", "Koninklijke Philips N.V. (ADR)", "ADR", "Health Care", "NL"),
    ("SPOT2", None, None, None, None),   # placeholder row, ignored
    # ---- Preferreds
    ("BAC-PL", "Bank of America 7.25% Series L Preferred", "PREFERRED", "Financials", "US"),
    ("WFC-PL", "Wells Fargo 7.50% Series L Preferred", "PREFERRED", "Financials", "US"),
    ("JPM-PC", "JPMorgan Chase 6.00% Series EE Preferred", "PREFERRED", "Financials", "US"),
    ("GS-PA", "Goldman Sachs Floating Series A Preferred", "PREFERRED", "Financials", "US"),
    ("MS-PA", "Morgan Stanley Floating Series A Preferred", "PREFERRED", "Financials", "US"),
]
STOCKS = [r for r in STOCKS if r[1]]

ETFS = [
    # broad index
    ("SPY", "SPDR S&P 500 ETF Trust", "ETF", "Index", "US"),
    ("QQQ", "Invesco QQQ Trust", "ETF", "Index", "US"),
    ("DIA", "SPDR Dow Jones Industrial Average ETF Trust", "ETF", "Index", "US"),
    ("IWM", "iShares Russell 2000 ETF", "ETF", "Index", "US"),
    ("MDY", "SPDR S&P MidCap 400 ETF Trust", "ETF", "Index", "US"),
    ("IJH", "iShares Core S&P Mid-Cap ETF", "ETF", "Index", "US"),
    ("IJR", "iShares Core S&P Small-Cap ETF", "ETF", "Index", "US"),
    ("VTI", "Vanguard Total Stock Market ETF", "ETF", "Index", "US"),
    ("VOO", "Vanguard S&P 500 ETF", "ETF", "Index", "US"),
    ("IVV", "iShares Core S&P 500 ETF", "ETF", "Index", "US"),
    ("RSP", "Invesco S&P 500 Equal Weight ETF", "ETF", "Index", "US"),
    # international
    ("VEA", "Vanguard FTSE Developed Markets ETF", "ETF", "International", "US"),
    ("VWO", "Vanguard FTSE Emerging Markets ETF", "ETF", "International", "US"),
    ("EFA", "iShares MSCI EAFE ETF", "ETF", "International", "US"),
    ("EEM", "iShares MSCI Emerging Markets ETF", "ETF", "International", "US"),
    ("IEFA", "iShares Core MSCI EAFE ETF", "ETF", "International", "US"),
    ("IEMG", "iShares Core MSCI Emerging Markets ETF", "ETF", "International", "US"),
    ("FXI", "iShares China Large-Cap ETF", "ETF", "International", "US"),
    ("MCHI", "iShares MSCI China ETF", "ETF", "International", "US"),
    ("KWEB", "KraneShares CSI China Internet ETF", "ETF", "International", "US"),
    ("EWJ", "iShares MSCI Japan ETF", "ETF", "International", "US"),
    ("EWZ", "iShares MSCI Brazil ETF", "ETF", "International", "US"),
    ("EWY", "iShares MSCI South Korea ETF", "ETF", "International", "US"),
    ("EWT", "iShares MSCI Taiwan ETF", "ETF", "International", "US"),
    ("EWG", "iShares MSCI Germany ETF", "ETF", "International", "US"),
    ("EWU", "iShares MSCI United Kingdom ETF", "ETF", "International", "US"),
    ("EWC", "iShares MSCI Canada ETF", "ETF", "International", "US"),
    ("EWA", "iShares MSCI Australia ETF", "ETF", "International", "US"),
    ("INDA", "iShares MSCI India ETF", "ETF", "International", "US"),
    ("EWW", "iShares MSCI Mexico ETF", "ETF", "International", "US"),
    ("VGK", "Vanguard FTSE Europe ETF", "ETF", "International", "US"),
    # sectors
    ("XLK", "Technology Select Sector SPDR Fund", "ETF", "Information Technology", "US"),
    ("XLF", "Financial Select Sector SPDR Fund", "ETF", "Financials", "US"),
    ("XLE", "Energy Select Sector SPDR Fund", "ETF", "Energy", "US"),
    ("XLV", "Health Care Select Sector SPDR Fund", "ETF", "Health Care", "US"),
    ("XLY", "Consumer Discretionary Select Sector SPDR Fund", "ETF", "Consumer Discretionary", "US"),
    ("XLP", "Consumer Staples Select Sector SPDR Fund", "ETF", "Consumer Staples", "US"),
    ("XLI", "Industrial Select Sector SPDR Fund", "ETF", "Industrials", "US"),
    ("XLB", "Materials Select Sector SPDR Fund", "ETF", "Materials", "US"),
    ("XLU", "Utilities Select Sector SPDR Fund", "ETF", "Utilities", "US"),
    ("XLRE", "Real Estate Select Sector SPDR Fund", "ETF", "Real Estate", "US"),
    ("XLC", "Communication Services Select Sector SPDR Fund", "ETF", "Communication Services", "US"),
    ("VNQ", "Vanguard Real Estate ETF", "ETF", "Real Estate", "US"),
    # industries and themes
    ("SMH", "VanEck Semiconductor ETF", "ETF", "Information Technology", "US"),
    ("SOXX", "iShares Semiconductor ETF", "ETF", "Information Technology", "US"),
    ("XBI", "SPDR S&P Biotech ETF", "ETF", "Health Care", "US"),
    ("IBB", "iShares Biotechnology ETF", "ETF", "Health Care", "US"),
    ("KRE", "SPDR S&P Regional Banking ETF", "ETF", "Financials", "US"),
    ("KBE", "SPDR S&P Bank ETF", "ETF", "Financials", "US"),
    ("XHB", "SPDR S&P Homebuilders ETF", "ETF", "Consumer Discretionary", "US"),
    ("ITB", "iShares U.S. Home Construction ETF", "ETF", "Consumer Discretionary", "US"),
    ("XRT", "SPDR S&P Retail ETF", "ETF", "Consumer Discretionary", "US"),
    ("XOP", "SPDR S&P Oil & Gas Exploration & Production ETF", "ETF", "Energy", "US"),
    ("OIH", "VanEck Oil Services ETF", "ETF", "Energy", "US"),
    ("JETS", "U.S. Global Jets ETF", "ETF", "Industrials", "US"),
    ("ITA", "iShares U.S. Aerospace & Defense ETF", "ETF", "Industrials", "US"),
    ("ARKK", "ARK Innovation ETF", "ETF", "Thematic", "US"),
    ("ICLN", "iShares Global Clean Energy ETF", "ETF", "Thematic", "US"),
    ("TAN", "Invesco Solar ETF", "ETF", "Thematic", "US"),
    ("LIT", "Global X Lithium & Battery Tech ETF", "ETF", "Thematic", "US"),
    ("BOTZ", "Global X Robotics & Artificial Intelligence ETF", "ETF", "Thematic", "US"),
    ("HACK", "Amplify Cybersecurity ETF", "ETF", "Thematic", "US"),
    ("URA", "Global X Uranium ETF", "ETF", "Thematic", "US"),
    # factors and income
    ("VUG", "Vanguard Growth ETF", "ETF", "Factor", "US"),
    ("VTV", "Vanguard Value ETF", "ETF", "Factor", "US"),
    ("IWF", "iShares Russell 1000 Growth ETF", "ETF", "Factor", "US"),
    ("IWD", "iShares Russell 1000 Value ETF", "ETF", "Factor", "US"),
    ("MTUM", "iShares MSCI USA Momentum Factor ETF", "ETF", "Factor", "US"),
    ("QUAL", "iShares MSCI USA Quality Factor ETF", "ETF", "Factor", "US"),
    ("USMV", "iShares MSCI USA Min Vol Factor ETF", "ETF", "Factor", "US"),
    ("VYM", "Vanguard High Dividend Yield ETF", "ETF", "Factor", "US"),
    ("SCHD", "Schwab U.S. Dividend Equity ETF", "ETF", "Factor", "US"),
    ("DVY", "iShares Select Dividend ETF", "ETF", "Factor", "US"),
    ("VIG", "Vanguard Dividend Appreciation ETF", "ETF", "Factor", "US"),
    ("JEPI", "JPMorgan Equity Premium Income ETF", "ETF", "Factor", "US"),
    ("JEPQ", "JPMorgan Nasdaq Equity Premium Income ETF", "ETF", "Factor", "US"),
    # bonds
    ("TLT", "iShares 20+ Year Treasury Bond ETF", "ETF", "Government", "US"),
    ("IEF", "iShares 7-10 Year Treasury Bond ETF", "ETF", "Government", "US"),
    ("SHY", "iShares 1-3 Year Treasury Bond ETF", "ETF", "Government", "US"),
    ("SHV", "iShares Short Treasury Bond ETF", "ETF", "Government", "US"),
    ("BIL", "SPDR Bloomberg 1-3 Month T-Bill ETF", "ETF", "Government", "US"),
    ("SGOV", "iShares 0-3 Month Treasury Bond ETF", "ETF", "Government", "US"),
    ("TLH", "iShares 10-20 Year Treasury Bond ETF", "ETF", "Government", "US"),
    ("VGIT", "Vanguard Intermediate-Term Treasury ETF", "ETF", "Government", "US"),
    ("AGG", "iShares Core U.S. Aggregate Bond ETF", "ETF", "Government", "US"),
    ("BND", "Vanguard Total Bond Market ETF", "ETF", "Government", "US"),
    ("BNDX", "Vanguard Total International Bond ETF", "ETF", "Government", "US"),
    ("TIP", "iShares TIPS Bond ETF", "ETF", "Government", "US"),
    ("MUB", "iShares National Muni Bond ETF", "ETF", "Government", "US"),
    ("LQD", "iShares iBoxx $ Investment Grade Corporate Bond ETF", "ETF", "Credit", "US"),
    ("VCIT", "Vanguard Intermediate-Term Corporate Bond ETF", "ETF", "Credit", "US"),
    ("VCSH", "Vanguard Short-Term Corporate Bond ETF", "ETF", "Credit", "US"),
    ("HYG", "iShares iBoxx $ High Yield Corporate Bond ETF", "ETF", "Credit", "US"),
    ("JNK", "SPDR Bloomberg High Yield Bond ETF", "ETF", "Credit", "US"),
    ("EMB", "iShares J.P. Morgan USD Emerging Markets Bond ETF", "ETF", "Credit", "US"),
    ("BKLN", "Invesco Senior Loan ETF", "ETF", "Credit", "US"),
    ("PFF", "iShares Preferred and Income Securities ETF", "ETF", "Credit", "US"),
    # commodities and metals
    ("GLD", "SPDR Gold Shares", "ETF", "Commodity", "US"),
    ("IAU", "iShares Gold Trust", "ETF", "Commodity", "US"),
    ("SLV", "iShares Silver Trust", "ETF", "Commodity", "US"),
    ("USO", "United States Oil Fund", "ETF", "Commodity", "US"),
    ("UNG", "United States Natural Gas Fund", "ETF", "Commodity", "US"),
    ("DBA", "Invesco DB Agriculture Fund", "ETF", "Commodity", "US"),
    ("DBC", "Invesco DB Commodity Index Tracking Fund", "ETF", "Commodity", "US"),
    ("PDBC", "Invesco Optimum Yield Diversified Commodity Strategy No K-1 ETF", "ETF", "Commodity", "US"),
    ("CPER", "United States Copper Index Fund", "ETF", "Commodity", "US"),
    ("GDX", "VanEck Gold Miners ETF", "ETF", "Materials", "US"),
    ("GDXJ", "VanEck Junior Gold Miners ETF", "ETF", "Materials", "US"),
    ("COPX", "Global X Copper Miners ETF", "ETF", "Materials", "US"),
    # crypto
    ("IBIT", "iShares Bitcoin Trust ETF", "ETF", "Crypto", "US"),
    ("FBTC", "Fidelity Wise Origin Bitcoin Fund", "ETF", "Crypto", "US"),
    ("ETHA", "iShares Ethereum Trust ETF", "ETF", "Crypto", "US"),
    ("BITO", "ProShares Bitcoin ETF", "ETF", "Crypto", "US"),
    # leveraged, inverse and volatility
    ("TQQQ", "ProShares UltraPro QQQ", "ETF", "Leveraged", "US"),
    ("SQQQ", "ProShares UltraPro Short QQQ", "ETF", "Leveraged", "US"),
    ("UPRO", "ProShares UltraPro S&P500", "ETF", "Leveraged", "US"),
    ("SPXU", "ProShares UltraPro Short S&P500", "ETF", "Leveraged", "US"),
    ("SOXL", "Direxion Daily Semiconductor Bull 3X Shares", "ETF", "Leveraged", "US"),
    ("SOXS", "Direxion Daily Semiconductor Bear 3X Shares", "ETF", "Leveraged", "US"),
    ("TNA", "Direxion Daily Small Cap Bull 3X Shares", "ETF", "Leveraged", "US"),
    ("SH", "ProShares Short S&P500", "ETF", "Leveraged", "US"),
    ("VXX", "iPath Series B S&P 500 VIX Short-Term Futures ETN", "ETF", "Volatility", "US"),
    ("UVXY", "ProShares Ultra VIX Short-Term Futures ETF", "ETF", "Volatility", "US"),
    ("SVXY", "ProShares Short VIX Short-Term Futures ETF", "ETF", "Volatility", "US"),
    ("UUP", "Invesco DB US Dollar Index Bullish Fund", "ETF", "Currency", "US"),
    ("FXE", "Invesco CurrencyShares Euro Trust", "ETF", "Currency", "US"),
    ("FXY", "Invesco CurrencyShares Japanese Yen Trust", "ETF", "Currency", "US"),
]

# crypto spot: ticker, name, Yahoo symbol
CRYPTO = [
    ("BTC", "Bitcoin", "CRYPTO", "Crypto", "XX", "BTC-USD"),
    ("ETH", "Ether", "CRYPTO", "Crypto", "XX", "ETH-USD"),
    ("SOL", "Solana", "CRYPTO", "Crypto", "XX", "SOL-USD"),
    ("XRP", "XRP", "CRYPTO", "Crypto", "XX", "XRP-USD"),
    ("BNB", "BNB", "CRYPTO", "Crypto", "XX", "BNB-USD"),
    ("ADA", "Cardano", "CRYPTO", "Crypto", "XX", "ADA-USD"),
    ("DOGE", "Dogecoin", "CRYPTO", "Crypto", "XX", "DOGE-USD"),
    ("AVAX", "Avalanche", "CRYPTO", "Crypto", "XX", "AVAX-USD"),
    ("LINK", "Chainlink", "CRYPTO", "Crypto", "XX", "LINK-USD"),
    ("DOT", "Polkadot", "CRYPTO", "Crypto", "XX", "DOT-USD"),
    ("LTC", "Litecoin", "CRYPTO", "Crypto", "XX", "LTC-USD"),
    ("BCH", "Bitcoin Cash", "CRYPTO", "Crypto", "XX", "BCH-USD"),
    ("TRX", "TRON", "CRYPTO", "Crypto", "XX", "TRX-USD"),
    ("XLM", "Stellar", "CRYPTO", "Crypto", "XX", "XLM-USD"),
    ("NEAR", "NEAR Protocol", "CRYPTO", "Crypto", "XX", "NEAR-USD"),
    ("ATOM", "Cosmos", "CRYPTO", "Crypto", "XX", "ATOM-USD"),
    ("HBAR", "Hedera", "CRYPTO", "Crypto", "XX", "HBAR-USD"),
    ("UNI", "Uniswap", "CRYPTO", "Crypto", "XX", "UNI7083-USD"),
    ("APT", "Aptos", "CRYPTO", "Crypto", "XX", "APT21794-USD"),
    ("ARB", "Arbitrum", "CRYPTO", "Crypto", "XX", "ARB11841-USD"),
    ("SUI", "Sui", "CRYPTO", "Crypto", "XX", "SUI20947-USD"),
    ("TON", "Toncoin", "CRYPTO", "Crypto", "XX", "TON11419-USD"),
    ("OP", "Optimism", "CRYPTO", "Crypto", "XX", "OP-USD"),
    ("AAVE", "Aave", "CRYPTO", "Crypto", "XX", "AAVE-USD"),
    ("ONDO", "Ondo", "CRYPTO", "Crypto", "XX", "ONDO-USD"),
    ("HYPE", "Hyperliquid", "CRYPTO", "Crypto", "XX", "HYPE32196-USD"),
    # stablecoins: dollar-pegged tokens (they trade, earn nothing here, and can be lent or posted as crypto collateral)
    ("USDT", "Tether USDt", "CRYPTO", "Stablecoin", "XX", "USDT-USD"),
    ("USDC", "USD Coin", "CRYPTO", "Stablecoin", "XX", "USDC-USD"),
    ("DAI", "Dai", "CRYPTO", "Stablecoin", "XX", "DAI-USD"),
]

UNIVERSE = STOCKS + ETFS + CRYPTO

# id, name, issuer, issuer ticker (None for sovereigns), coupon, years to maturity, rating, spread bps, ADV face, sector
BONDS = [
    # financials
    ("JPM-29", "JPMorgan Chase 4.85% 2029", "JPMorgan Chase & Co.", "JPM", 0.0485, 3.0, "A", 80.0, 25_000_000, "Financials"),
    ("JPM-35", "JPMorgan Chase 5.35% 2035", "JPMorgan Chase & Co.", "JPM", 0.0535, 9.0, "A", 105.0, 20_000_000, "Financials"),
    ("BAC-30", "Bank of America 4.95% 2030", "Bank of America Corporation", "BAC", 0.0495, 4.0, "A-", 95.0, 25_000_000, "Financials"),
    ("BAC-41", "Bank of America 5.50% 2041", "Bank of America Corporation", "BAC", 0.055, 15.0, "A-", 135.0, 12_000_000, "Financials"),
    ("GS-31", "Goldman Sachs 5.10% 2031", "The Goldman Sachs Group, Inc.", "GS", 0.051, 5.0, "BBB+", 110.0, 20_000_000, "Financials"),
    ("MS-30", "Morgan Stanley 5.05% 2030", "Morgan Stanley", "MS", 0.0505, 4.0, "A-", 100.0, 20_000_000, "Financials"),
    ("C-32", "Citigroup 5.30% 2032", "Citigroup Inc.", "C", 0.053, 6.0, "BBB+", 120.0, 20_000_000, "Financials"),
    ("WFC-31", "Wells Fargo 4.90% 2031", "Wells Fargo & Company", "WFC", 0.049, 5.0, "BBB+", 95.0, 20_000_000, "Financials"),
    ("USB-29", "U.S. Bancorp 4.65% 2029", "U.S. Bancorp", "USB", 0.0465, 3.0, "A", 85.0, 12_000_000, "Financials"),
    ("PNC-30", "PNC Financial 4.80% 2030", "The PNC Financial Services Group, Inc.", "PNC", 0.048, 4.0, "A-", 95.0, 10_000_000, "Financials"),
    ("TFC-31", "Truist Financial 5.00% 2031", "Truist Financial Corporation", "TFC", 0.05, 5.0, "A-", 110.0, 8_000_000, "Financials"),
    ("COF-30", "Capital One 5.25% 2030", "Capital One Financial Corporation", "COF", 0.0525, 4.0, "BBB", 130.0, 10_000_000, "Financials"),
    ("AXP-29", "American Express 4.70% 2029", "American Express Company", "AXP", 0.047, 3.0, "A-", 75.0, 12_000_000, "Financials"),
    ("SCHW-30", "Charles Schwab 4.90% 2030", "The Charles Schwab Corporation", "SCHW", 0.049, 4.0, "A", 90.0, 8_000_000, "Financials"),
    ("BLK-34", "BlackRock 5.00% 2034", "BlackRock, Inc.", "BLK", 0.05, 8.0, "AA-", 75.0, 8_000_000, "Financials"),
    ("MET-33", "MetLife 5.15% 2033", "MetLife, Inc.", "MET", 0.0515, 7.0, "A-", 100.0, 8_000_000, "Financials"),
    ("PRU-32", "Prudential Financial 5.10% 2032", "Prudential Financial, Inc.", "PRU", 0.051, 6.0, "A", 95.0, 8_000_000, "Financials"),
    ("AIG-31", "American International Group 4.90% 2031", "American International Group, Inc.", "AIG", 0.049, 5.0, "A-", 105.0, 8_000_000, "Financials"),
    ("ALLY-29", "Ally Financial 6.70% 2029", "Ally Financial Inc.", "ALLY", 0.067, 3.0, "BBB-", 200.0, 6_000_000, "Financials"),
    ("SYF-30", "Synchrony Financial 5.95% 2030", "Synchrony Financial", "SYF", 0.0595, 4.0, "BBB-", 185.0, 6_000_000, "Financials"),
    ("KKR-33", "KKR Group 5.20% 2033", "KKR & Co. Inc.", "KKR", 0.052, 7.0, "A", 95.0, 5_000_000, "Financials"),
    ("BX-34", "Blackstone 5.10% 2034", "Blackstone Inc.", "BX", 0.051, 8.0, "A+", 90.0, 5_000_000, "Financials"),
    ("COIN-31", "Coinbase 3.625% 2031", "Coinbase Global, Inc.", "COIN", 0.03625, 5.0, "BB", 300.0, 5_000_000, "Financials"),
    ("MSTR-32", "Strategy 0.625% 2032 (convertible-style)", "Strategy Inc.", "MSTR", 0.00625, 6.0, "B-", 520.0, 4_000_000, "Information Technology"),
    # technology and communications
    ("MSFT-27", "Microsoft 3.30% 2027", "Microsoft Corporation", "MSFT", 0.033, 1.0, "AAA", 35.0, 30_000_000, "Information Technology"),
    ("MSFT-52", "Microsoft 3.04% 2052", "Microsoft Corporation", "MSFT", 0.0304, 26.0, "AAA", 70.0, 15_000_000, "Information Technology"),
    ("AAPL-31", "Apple 2.65% 2031", "Apple Inc.", "AAPL", 0.0265, 5.0, "AA+", 50.0, 25_000_000, "Information Technology"),
    ("AAPL-46", "Apple 4.65% 2046", "Apple Inc.", "AAPL", 0.0465, 20.0, "AA+", 70.0, 20_000_000, "Information Technology"),
    ("ORCL-34", "Oracle 5.60% 2034", "Oracle Corporation", "ORCL", 0.056, 8.0, "BBB", 135.0, 20_000_000, "Information Technology"),
    ("ORCL-54", "Oracle 6.10% 2054", "Oracle Corporation", "ORCL", 0.061, 28.0, "BBB", 175.0, 10_000_000, "Information Technology"),
    ("AVGO-33", "Broadcom 4.80% 2033", "Broadcom Inc.", "AVGO", 0.048, 7.0, "BBB", 110.0, 15_000_000, "Information Technology"),
    ("CSCO-35", "Cisco Systems 5.05% 2035", "Cisco Systems, Inc.", "CSCO", 0.0505, 9.0, "AA-", 65.0, 10_000_000, "Information Technology"),
    ("IBM-33", "IBM 4.90% 2033", "International Business Machines Corporation", "IBM", 0.049, 7.0, "A-", 95.0, 12_000_000, "Information Technology"),
    ("INTC-34", "Intel 5.20% 2034", "Intel Corporation", "INTC", 0.052, 8.0, "BBB", 160.0, 12_000_000, "Information Technology"),
    ("QCOM-32", "Qualcomm 4.25% 2032", "QUALCOMM Incorporated", "QCOM", 0.0425, 6.0, "A", 70.0, 8_000_000, "Information Technology"),
    ("DELL-31", "Dell International 5.30% 2031", "Dell Technologies Inc.", "DELL", 0.053, 5.0, "BBB", 115.0, 6_000_000, "Information Technology"),
    ("CRM-31", "Salesforce 2.90% 2031", "Salesforce, Inc.", "CRM", 0.029, 5.0, "A+", 60.0, 8_000_000, "Information Technology"),
    ("AMZN-34", "Amazon 4.70% 2034", "Amazon.com, Inc.", "AMZN", 0.047, 8.0, "AA", 60.0, 20_000_000, "Consumer Discretionary"),
    ("AMZN-61", "Amazon 3.10% 2061", "Amazon.com, Inc.", "AMZN", 0.031, 35.0, "AA", 95.0, 8_000_000, "Consumer Discretionary"),
    ("GOOGL-30", "Alphabet 4.25% 2030", "Alphabet Inc.", "GOOGL", 0.0425, 4.0, "AA+", 40.0, 15_000_000, "Communication Services"),
    ("META-33", "Meta Platforms 4.95% 2033", "Meta Platforms, Inc.", "META", 0.0495, 7.0, "AA-", 65.0, 15_000_000, "Communication Services"),
    ("META-53", "Meta Platforms 5.75% 2053", "Meta Platforms, Inc.", "META", 0.0575, 27.0, "AA-", 100.0, 8_000_000, "Communication Services"),
    ("NFLX-30", "Netflix 4.875% 2030", "Netflix, Inc.", "NFLX", 0.04875, 4.0, "A", 80.0, 8_000_000, "Communication Services"),
    ("T-30", "AT&T 4.30% 2030", "AT&T Inc.", "T", 0.043, 4.0, "BBB", 120.0, 25_000_000, "Communication Services"),
    ("T-53", "AT&T 5.40% 2053", "AT&T Inc.", "T", 0.054, 27.0, "BBB", 175.0, 12_000_000, "Communication Services"),
    ("VZ-34", "Verizon 4.40% 2034", "Verizon Communications Inc.", "VZ", 0.044, 8.0, "BBB+", 115.0, 20_000_000, "Communication Services"),
    ("TMUS-33", "T-Mobile USA 5.05% 2033", "T-Mobile US, Inc.", "TMUS", 0.0505, 7.0, "BBB", 120.0, 12_000_000, "Communication Services"),
    ("CMCSA-35", "Comcast 5.10% 2035", "Comcast Corporation", "CMCSA", 0.051, 9.0, "A-", 100.0, 12_000_000, "Communication Services"),
    ("CHTR-33", "Charter Communications 6.10% 2033", "Charter Communications, Inc.", "CHTR", 0.061, 7.0, "BB+", 240.0, 10_000_000, "Communication Services"),
    ("WBD-32", "Warner Bros. Discovery 4.28% 2032", "Warner Bros. Discovery, Inc.", "WBD", 0.0428, 6.0, "BB+", 330.0, 12_000_000, "Communication Services"),
    ("DIS-33", "Walt Disney 4.70% 2033", "The Walt Disney Company", "DIS", 0.047, 7.0, "A-", 95.0, 10_000_000, "Communication Services"),
    ("LUMN-29", "Lumen Technologies 10.50% 2029", "Lumen Technologies, Inc.", "LUMN", 0.105, 3.0, "CCC+", 800.0, 4_000_000, "Communication Services"),
    # consumer
    ("HD-33", "Home Depot 4.95% 2033", "The Home Depot, Inc.", "HD", 0.0495, 7.0, "A", 75.0, 10_000_000, "Consumer Discretionary"),
    ("LOW-34", "Lowe's 5.00% 2034", "Lowe's Companies, Inc.", "LOW", 0.05, 8.0, "BBB+", 100.0, 8_000_000, "Consumer Discretionary"),
    ("MCD-34", "McDonald's 4.95% 2034", "McDonald's Corporation", "MCD", 0.0495, 8.0, "BBB+", 90.0, 8_000_000, "Consumer Discretionary"),
    ("SBUX-33", "Starbucks 4.85% 2033", "Starbucks Corporation", "SBUX", 0.0485, 7.0, "BBB", 110.0, 6_000_000, "Consumer Discretionary"),
    ("NKE-33", "NIKE 3.25% 2033", "NIKE, Inc.", "NKE", 0.0325, 7.0, "AA-", 70.0, 6_000_000, "Consumer Discretionary"),
    ("F-32", "Ford Motor Credit 6.10% 2032", "Ford Motor Credit Company", "F", 0.061, 6.0, "BBB-", 190.0, 18_000_000, "Consumer Discretionary"),
    ("GM-29", "General Motors Financial 5.40% 2029", "General Motors Financial Company", "GM", 0.054, 3.0, "BBB", 140.0, 15_000_000, "Consumer Discretionary"),
    ("TSLA-30", "Tesla 5.30% 2030", "Tesla, Inc.", "TSLA", 0.053, 4.0, "BBB", 130.0, 6_000_000, "Consumer Discretionary"),
    ("RIVN-29", "Rivian 8.75% 2029", "Rivian Automotive, Inc.", "RIVN", 0.0875, 3.0, "B-", 520.0, 4_000_000, "Consumer Discretionary"),
    ("CCL-30", "Carnival 5.75% 2030", "Carnival Corporation", "CCL", 0.0575, 4.0, "BB+", 260.0, 10_000_000, "Consumer Discretionary"),
    ("RCL-30", "Royal Caribbean 5.625% 2031", "Royal Caribbean Cruises Ltd.", "RCL", 0.05625, 5.0, "BB+", 240.0, 8_000_000, "Consumer Discretionary"),
    ("MAR-32", "Marriott 4.90% 2032", "Marriott International, Inc.", "MAR", 0.049, 6.0, "BBB", 115.0, 6_000_000, "Consumer Discretionary"),
    ("HLT-31", "Hilton 5.875% 2031", "Hilton Worldwide Holdings Inc.", "HLT", 0.05875, 5.0, "BB+", 210.0, 5_000_000, "Consumer Discretionary"),
    ("MGM-30", "MGM Resorts 6.50% 2030", "MGM Resorts International", "MGM", 0.065, 4.0, "BB-", 300.0, 5_000_000, "Consumer Discretionary"),
    ("CVNA-30", "Carvana 9.00% 2030", "Carvana Co.", "CVNA", 0.09, 4.0, "B", 550.0, 4_000_000, "Consumer Discretionary"),
    ("W-30", "Wayfair 7.75% 2030", "Wayfair Inc.", "W", 0.0775, 4.0, "B+", 480.0, 3_000_000, "Consumer Discretionary"),
    ("KHC-30", "Kraft Heinz 3.875% 2030", "The Kraft Heinz Company", "KHC", 0.03875, 4.0, "BBB", 145.0, 10_000_000, "Consumer Staples"),
    ("PG-33", "Procter & Gamble 4.15% 2033", "The Procter & Gamble Company", "PG", 0.0415, 7.0, "AA-", 50.0, 10_000_000, "Consumer Staples"),
    ("KO-34", "Coca-Cola 4.65% 2034", "The Coca-Cola Company", "KO", 0.0465, 8.0, "A+", 65.0, 10_000_000, "Consumer Staples"),
    ("PEP-34", "PepsiCo 4.70% 2034", "PepsiCo, Inc.", "PEP", 0.047, 8.0, "A+", 65.0, 10_000_000, "Consumer Staples"),
    ("WMT-34", "Walmart 4.50% 2034", "Walmart Inc.", "WMT", 0.045, 8.0, "AA", 50.0, 12_000_000, "Consumer Staples"),
    ("COST-31", "Costco 1.75% 2031", "Costco Wholesale Corporation", "COST", 0.0175, 5.0, "AA", 45.0, 6_000_000, "Consumer Staples"),
    ("PM-34", "Philip Morris 5.25% 2034", "Philip Morris International Inc.", "PM", 0.0525, 8.0, "A-", 100.0, 8_000_000, "Consumer Staples"),
    ("MO-33", "Altria 5.40% 2033", "Altria Group, Inc.", "MO", 0.054, 7.0, "BBB", 140.0, 8_000_000, "Consumer Staples"),
    ("TGT-33", "Target 4.80% 2033", "Target Corporation", "TGT", 0.048, 7.0, "A", 90.0, 6_000_000, "Consumer Staples"),
    ("KR-31", "Kroger 4.65% 2031", "The Kroger Co.", "KR", 0.0465, 5.0, "BBB", 110.0, 5_000_000, "Consumer Staples"),
    ("BYND-27", "Beyond Meat 0% 2027 (convertible-style)", "Beyond Meat, Inc.", "BYND", 0.0, 1.0, "CCC", 1800.0, 2_000_000, "Consumer Staples"),
    # health care
    ("LLY-34", "Eli Lilly 4.70% 2034", "Eli Lilly and Company", "LLY", 0.047, 8.0, "A+", 60.0, 10_000_000, "Health Care"),
    ("UNH-34", "UnitedHealth 5.15% 2034", "UnitedHealth Group Incorporated", "UNH", 0.0515, 8.0, "A", 105.0, 12_000_000, "Health Care"),
    ("JNJ-33", "Johnson & Johnson 4.55% 2033", "Johnson & Johnson", "JNJ", 0.0455, 7.0, "AAA", 40.0, 10_000_000, "Health Care"),
    ("PFE-33", "Pfizer 4.75% 2033", "Pfizer Inc.", "PFE", 0.0475, 7.0, "A", 85.0, 12_000_000, "Health Care"),
    ("MRK-34", "Merck 4.90% 2034", "Merck & Co., Inc.", "MRK", 0.049, 8.0, "A+", 60.0, 8_000_000, "Health Care"),
    ("ABBV-33", "AbbVie 4.95% 2033", "AbbVie Inc.", "ABBV", 0.0495, 7.0, "A-", 85.0, 12_000_000, "Health Care"),
    ("AMGN-33", "Amgen 5.25% 2033", "Amgen Inc.", "AMGN", 0.0525, 7.0, "BBB+", 100.0, 10_000_000, "Health Care"),
    ("BMY-33", "Bristol-Myers Squibb 5.20% 2033", "Bristol-Myers Squibb Company", "BMY", 0.052, 7.0, "A", 95.0, 8_000_000, "Health Care"),
    ("CVS-33", "CVS Health 5.25% 2033", "CVS Health Corporation", "CVS", 0.0525, 7.0, "BBB", 150.0, 15_000_000, "Health Care"),
    ("CI-33", "Cigna 5.00% 2033", "The Cigna Group", "CI", 0.05, 7.0, "A-", 100.0, 6_000_000, "Health Care"),
    ("HCA-33", "HCA Healthcare 5.50% 2033", "HCA Healthcare, Inc.", "HCA", 0.055, 7.0, "BBB-", 150.0, 6_000_000, "Health Care"),
    ("MRNA-29", "Moderna 5.50% 2029 (convertible-style, unsecured)", "Moderna, Inc.", "MRNA", 0.055, 3.0, "B", 600.0, 5_000_000, "Health Care"),
    ("BAX-30", "Baxter 5.75% 2030", "Baxter International Inc.", "BAX", 0.0575, 4.0, "BBB-", 170.0, 4_000_000, "Health Care"),
    # industrials, energy, materials, utilities
    ("BA-30", "Boeing 5.15% 2030", "The Boeing Company", "BA", 0.0515, 4.0, "BBB-", 165.0, 15_000_000, "Industrials"),
    ("BA-60", "Boeing 5.805% 2060", "The Boeing Company", "BA", 0.05805, 34.0, "BBB-", 230.0, 6_000_000, "Industrials"),
    ("AAL-28", "American Airlines 7.25% 2028", "American Airlines Group Inc.", "AAL", 0.0725, 2.5, "B+", 420.0, 8_000_000, "Industrials"),
    ("DAL-29", "Delta Air Lines 7.00% 2029", "Delta Air Lines, Inc.", "DAL", 0.07, 3.0, "BB+", 280.0, 8_000_000, "Industrials"),
    ("UAL-29", "United Airlines 4.375% 2029", "United Airlines Holdings, Inc.", "UAL", 0.04375, 3.0, "BB", 260.0, 5_000_000, "Industrials"),
    ("GE-32", "GE Aerospace 4.35% 2032", "GE Aerospace", "GE", 0.0435, 6.0, "A-", 80.0, 8_000_000, "Industrials"),
    ("CAT-34", "Caterpillar Financial 4.85% 2034", "Caterpillar Inc.", "CAT", 0.0485, 8.0, "A", 70.0, 8_000_000, "Industrials"),
    ("UPS-34", "United Parcel Service 5.05% 2034", "United Parcel Service, Inc.", "UPS", 0.0505, 8.0, "A", 80.0, 6_000_000, "Industrials"),
    ("FDX-34", "FedEx 5.10% 2034", "FedEx Corporation", "FDX", 0.051, 8.0, "BBB", 115.0, 6_000_000, "Industrials"),
    ("RTX-34", "RTX 5.15% 2034", "RTX Corporation", "RTX", 0.0515, 8.0, "BBB+", 100.0, 8_000_000, "Industrials"),
    ("LMT-34", "Lockheed Martin 4.75% 2034", "Lockheed Martin Corporation", "LMT", 0.0475, 8.0, "A-", 80.0, 6_000_000, "Industrials"),
    ("UNP-34", "Union Pacific 4.85% 2034", "Union Pacific Corporation", "UNP", 0.0485, 8.0, "A-", 80.0, 6_000_000, "Industrials"),
    ("DE-33", "John Deere Capital 4.70% 2033", "Deere & Company", "DE", 0.047, 7.0, "A", 70.0, 6_000_000, "Industrials"),
    ("URI-31", "United Rentals 6.00% 2031", "United Rentals, Inc.", "URI", 0.06, 5.0, "BB+", 220.0, 5_000_000, "Industrials"),
    ("XOM-51", "Exxon Mobil 3.45% 2051", "Exxon Mobil Corporation", "XOM", 0.0345, 25.0, "AA-", 85.0, 15_000_000, "Energy"),
    ("XOM-31", "Exxon Mobil 2.61% 2031", "Exxon Mobil Corporation", "XOM", 0.0261, 5.0, "AA-", 55.0, 15_000_000, "Energy"),
    ("CVX-33", "Chevron 4.85% 2033", "Chevron Corporation", "CVX", 0.0485, 7.0, "AA-", 55.0, 10_000_000, "Energy"),
    ("COP-34", "ConocoPhillips 5.05% 2034", "ConocoPhillips", "COP", 0.0505, 8.0, "A-", 85.0, 8_000_000, "Energy"),
    ("OXY-31", "Occidental Petroleum 6.125% 2031", "Occidental Petroleum Corporation", "OXY", 0.06125, 5.0, "BB+", 230.0, 10_000_000, "Energy"),
    ("KMI-33", "Kinder Morgan 5.20% 2033", "Kinder Morgan, Inc.", "KMI", 0.052, 7.0, "BBB", 130.0, 6_000_000, "Energy"),
    ("WMB-34", "Williams Companies 5.15% 2034", "The Williams Companies, Inc.", "WMB", 0.0515, 8.0, "BBB", 125.0, 6_000_000, "Energy"),
    ("DVN-32", "Devon Energy 5.60% 2032", "Devon Energy Corporation", "DVN", 0.056, 6.0, "BBB", 150.0, 5_000_000, "Energy"),
    ("LNG-33", "Cheniere Energy 5.65% 2033", "Cheniere Energy, Inc.", "LNG", 0.0565, 7.0, "BBB", 145.0, 5_000_000, "Energy"),
    ("APA-30", "APA Corporation 5.10% 2030", "APA Corporation", "APA", 0.051, 4.0, "BB+", 250.0, 4_000_000, "Energy"),
    ("FCX-31", "Freeport-McMoRan 5.40% 2031", "Freeport-McMoRan Inc.", "FCX", 0.054, 5.0, "BBB-", 155.0, 6_000_000, "Materials"),
    ("NEM-33", "Newmont 5.30% 2033", "Newmont Corporation", "NEM", 0.053, 7.0, "BBB+", 110.0, 5_000_000, "Materials"),
    ("DOW-33", "Dow Chemical 5.15% 2033", "Dow Inc.", "DOW", 0.0515, 7.0, "BBB", 140.0, 6_000_000, "Materials"),
    ("NUE-33", "Nucor 4.95% 2033", "Nucor Corporation", "NUE", 0.0495, 7.0, "A-", 90.0, 4_000_000, "Materials"),
    ("CLF-31", "Cleveland-Cliffs 7.00% 2031", "Cleveland-Cliffs Inc.", "CLF", 0.07, 5.0, "BB-", 380.0, 4_000_000, "Materials"),
    ("ALB-31", "Albemarle 5.05% 2031", "Albemarle Corporation", "ALB", 0.0505, 5.0, "BBB-", 180.0, 3_000_000, "Materials"),
    ("NEE-34", "NextEra Energy Capital 5.05% 2034", "NextEra Energy, Inc.", "NEE", 0.0505, 8.0, "A-", 95.0, 8_000_000, "Utilities"),
    ("DUK-34", "Duke Energy 5.00% 2034", "Duke Energy Corporation", "DUK", 0.05, 8.0, "BBB+", 100.0, 8_000_000, "Utilities"),
    ("SO-33", "Southern Company 5.20% 2033", "The Southern Company", "SO", 0.052, 7.0, "BBB+", 105.0, 6_000_000, "Utilities"),
    ("D-34", "Dominion Energy 5.30% 2034", "Dominion Energy, Inc.", "D", 0.053, 8.0, "BBB", 120.0, 6_000_000, "Utilities"),
    ("PCG-33", "Pacific Gas & Electric 5.90% 2033", "PG&E Corporation", "PCG", 0.059, 7.0, "BBB-", 170.0, 6_000_000, "Utilities"),
    ("VST-31", "Vistra Operations 5.70% 2031", "Vistra Corp.", "VST", 0.057, 5.0, "BB+", 200.0, 4_000_000, "Utilities"),
    ("AMT-34", "American Tower 5.20% 2034", "American Tower Corporation", "AMT", 0.052, 8.0, "BBB-", 130.0, 6_000_000, "Real Estate"),
    ("PLD-34", "Prologis 4.75% 2034", "Prologis, Inc.", "PLD", 0.0475, 8.0, "A", 80.0, 5_000_000, "Real Estate"),
    ("O-34", "Realty Income 5.125% 2034", "Realty Income Corporation", "O", 0.05125, 8.0, "A-", 110.0, 5_000_000, "Real Estate"),
    ("SPG-33", "Simon Property 5.50% 2033", "Simon Property Group, Inc.", "SPG", 0.055, 7.0, "A-", 115.0, 4_000_000, "Real Estate"),
    # foreign corporates in USD
    ("TM-29", "Toyota Motor Credit 4.55% 2029", "Toyota Motor Corporation", "TM", 0.0455, 3.0, "A+", 60.0, 8_000_000, "Consumer Discretionary"),
    ("SHEL-34", "Shell International Finance 4.75% 2034", "Shell plc", "SHEL", 0.0475, 8.0, "AA-", 70.0, 6_000_000, "Energy"),
    ("BP-33", "BP Capital Markets 4.95% 2033", "BP p.l.c.", "BP", 0.0495, 7.0, "A-", 95.0, 5_000_000, "Energy"),
    ("HSBC-33", "HSBC Holdings 5.40% 2033", "HSBC Holdings plc", "HSBC", 0.054, 7.0, "A-", 115.0, 6_000_000, "Financials"),
    ("DB-30", "Deutsche Bank 6.10% 2030", "Deutsche Bank Aktiengesellschaft", "DB", 0.061, 4.0, "BBB", 185.0, 4_000_000, "Financials"),
    ("UBS-32", "UBS Group 5.20% 2032", "UBS Group AG", "UBS", 0.052, 6.0, "A-", 110.0, 5_000_000, "Financials"),
    ("BABA-31", "Alibaba 2.70% 2031", "Alibaba Group Holding Limited", "BABA", 0.027, 5.0, "A+", 110.0, 5_000_000, "Consumer Discretionary"),
    ("PBR-33", "Petrobras Global Finance 6.50% 2033", "Petróleo Brasileiro S.A. - Petrobras", "PBR", 0.065, 7.0, "BB", 280.0, 5_000_000, "Energy"),
    ("VALE-34", "Vale Overseas 6.125% 2034", "Vale S.A.", "VALE", 0.06125, 8.0, "BBB-", 190.0, 4_000_000, "Materials"),
    # sovereigns in USD (no equity ticker)
    ("SOV-US-MX-34", "United Mexican States 6.00% 2034", "United Mexican States", None, 0.06, 8.0, "BBB", 190.0, 15_000_000, "Sovereign"),
    ("SOV-US-BR-34", "Federative Republic of Brazil 6.25% 2034", "Federative Republic of Brazil", None, 0.0625, 8.0, "BB", 250.0, 12_000_000, "Sovereign"),
    ("SOV-US-IT-33", "Republic of Italy 5.375% 2033", "Republic of Italy", None, 0.05375, 7.0, "BBB", 130.0, 8_000_000, "Sovereign"),
    ("SOV-US-ID-34", "Republic of Indonesia 5.10% 2034", "Republic of Indonesia", None, 0.051, 8.0, "BBB", 120.0, 8_000_000, "Sovereign"),
    ("SOV-US-TR-30", "Republic of Türkiye 7.625% 2030", "Republic of Türkiye", None, 0.07625, 4.0, "BB-", 320.0, 8_000_000, "Sovereign"),
    ("SOV-US-AR-35", "Argentine Republic 4.125% 2035 step-up", "Argentine Republic", None, 0.04125, 9.0, "CCC", 750.0, 6_000_000, "Sovereign"),
    ("SOV-US-SA-34", "Kingdom of Saudi Arabia 5.00% 2034", "Kingdom of Saudi Arabia", None, 0.05, 8.0, "A+", 95.0, 10_000_000, "Sovereign"),
    ("SOV-US-CO-34", "Republic of Colombia 8.00% 2034", "Republic of Colombia", None, 0.08, 8.0, "BB", 330.0, 6_000_000, "Sovereign"),
    ("SOV-US-ZA-33", "Republic of South Africa 5.875% 2033", "Republic of South Africa", None, 0.05875, 7.0, "BB-", 300.0, 6_000_000, "Sovereign"),
    ("SOV-US-CL-33", "Republic of Chile 4.85% 2033", "Republic of Chile", None, 0.0485, 7.0, "A", 100.0, 6_000_000, "Sovereign"),
    ("SOV-US-PE-33", "Republic of Peru 5.375% 2033", "Republic of Peru", None, 0.05375, 7.0, "BBB-", 150.0, 5_000_000, "Sovereign"),
    ("SOV-US-PH-34", "Republic of the Philippines 5.00% 2034", "Republic of the Philippines", None, 0.05, 8.0, "BBB+", 105.0, 5_000_000, "Sovereign"),
    ("SOV-US-IL-33", "State of Israel 5.75% 2033", "State of Israel", None, 0.0575, 7.0, "A", 135.0, 5_000_000, "Sovereign"),
    ("SOV-US-EG-31", "Arab Republic of Egypt 7.625% 2031", "Arab Republic of Egypt", None, 0.07625, 5.0, "B-", 600.0, 4_000_000, "Sovereign"),
    ("SOV-US-NG-33", "Federal Republic of Nigeria 7.875% 2033", "Federal Republic of Nigeria", None, 0.07875, 7.0, "B-", 620.0, 4_000_000, "Sovereign"),
    ("SOV-US-PL-34", "Republic of Poland 5.125% 2034", "Republic of Poland", None, 0.05125, 8.0, "A-", 105.0, 5_000_000, "Sovereign"),
    ("SOV-US-QA-34", "State of Qatar 4.75% 2034", "State of Qatar", None, 0.0475, 8.0, "AA", 75.0, 5_000_000, "Sovereign"),
    ("SOV-US-CN-34", "People's Republic of China 4.25% 2034", "People's Republic of China", None, 0.0425, 8.0, "A+", 60.0, 5_000_000, "Sovereign"),
    ("SOV-US-JP-34", "Japan Bank for International Cooperation 4.50% 2034", "Japan (JBIC)", None, 0.045, 8.0, "A+", 45.0, 5_000_000, "Sovereign"),
    ("SOV-US-DE-34", "KfW 4.375% 2034", "Germany (KfW)", None, 0.04375, 8.0, "AAA", 25.0, 8_000_000, "Sovereign"),
    # municipal and agency issues (tax treatment is not modelled: they price as credits off the curve)
    ("MUNI-CA-35", "State of California GO 4.00% 2035", "State of California", None, 0.04, 9.0, "AA-", 55.0, 6_000_000, "Municipal"),
    ("MUNI-NYC-34", "New York City GO 4.25% 2034", "City of New York", None, 0.0425, 8.0, "AA", 50.0, 5_000_000, "Municipal"),
    ("MUNI-TX-33", "State of Texas GO 3.75% 2033", "State of Texas", None, 0.0375, 7.0, "AAA", 35.0, 4_000_000, "Municipal"),
    ("MUNI-IL-33", "State of Illinois GO 5.50% 2033", "State of Illinois", None, 0.055, 7.0, "A-", 140.0, 4_000_000, "Municipal"),
    ("MUNI-PR-41", "Puerto Rico GO 5.75% 2041 (restructured)", "Commonwealth of Puerto Rico", None, 0.0575, 15.0, "B", 520.0, 3_000_000, "Municipal"),
    ("AGY-FHLB-29", "Federal Home Loan Banks 4.50% 2029", "Federal Home Loan Banks", None, 0.045, 3.0, "AA+", 15.0, 20_000_000, "Agency"),
    ("AGY-FNMA-31", "Fannie Mae 4.75% 2031", "Federal National Mortgage Association", None, 0.0475, 5.0, "AA+", 20.0, 15_000_000, "Agency"),
    ("AGY-FHLMC-34", "Freddie Mac 4.90% 2034", "Federal Home Loan Mortgage Corporation", None, 0.049, 8.0, "AA+", 25.0, 12_000_000, "Agency"),
    ("AGY-TVA-36", "Tennessee Valley Authority 5.00% 2036", "Tennessee Valley Authority", None, 0.05, 10.0, "AA+", 30.0, 5_000_000, "Agency"),
]

# circulating supply in millions of coins (approximate, for market-cap tiers only)
CRYPTO_SUPPLY_M = {"BTC": 19.9, "ETH": 120.7, "SOL": 545.0, "XRP": 59_500.0, "BNB": 139.0, "ADA": 35_800.0, "DOGE": 150_000.0, "AVAX": 425.0, "LINK": 680.0,
                   "DOT": 1_600.0, "LTC": 76.3, "BCH": 19.9, "TRX": 94_700.0, "XLM": 31_300.0, "NEAR": 1_240.0, "ATOM": 470.0, "HBAR": 42_400.0,
                   "SHIB": 589_000_000.0, "UNI": 630.0, "APT": 660.0, "ARB": 5_100.0, "SUI": 3_500.0, "TON": 2_500.0, "OP": 1_800.0, "AAVE": 15.2,
                   "ONDO": 3_160.0, "HYPE": 335.0, "USDT": 175_000.0, "USDC": 74_000.0, "DAI": 5_300.0}
